/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GameserverGameSeasonDto
 */
export class GameserverGameSeasonDto {
    /**
     *
     * @type {number}
     * @memberof GameserverGameSeasonDto
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof GameserverGameSeasonDto
     */
    startTimestamp: string;
    /**
     *
     * @type {boolean}
     * @memberof GameserverGameSeasonDto
     */
    isActive: boolean;
}

export function GameserverGameSeasonDtoFromJSON(json: any): GameserverGameSeasonDto {
    return GameserverGameSeasonDtoFromJSONTyped(json, false);
}

export function GameserverGameSeasonDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverGameSeasonDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'startTimestamp': json['startTimestamp'],
        'isActive': json['isActive'],
    };
}

export function GameserverGameSeasonDtoToJSON(value?: GameserverGameSeasonDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'startTimestamp': value.startTimestamp,
        'isActive': value.isActive,
    };
}


