// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GameserverReportPlayerDto
 */
export interface GameserverReportPlayerDto {
    /**
     * 
     * @type {object}
     * @memberof GameserverReportPlayerDto
     */
    reported: object;
    /**
     * 
     * @type {object}
     * @memberof GameserverReportPlayerDto
     */
    reporter: object;
    /**
     * 
     * @type {string}
     * @memberof GameserverReportPlayerDto
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof GameserverReportPlayerDto
     */
    matchId: number;
}


