/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameserverBanReason, GameserverBanReasonFromJSON, GameserverBanReasonToJSON } from './';

/**
 *
 * @export
 * @interface GameserverBanStatusDto
 */
export class GameserverBanStatusDto {
    /**
     *
     * @type {GameserverBanReason}
     * @memberof GameserverBanStatusDto
     */
    status: GameserverBanReason;
    /**
     *
     * @type {string}
     * @memberof GameserverBanStatusDto
     */
    steam_id: string;
    /**
     *
     * @type {boolean}
     * @memberof GameserverBanStatusDto
     */
    isBanned: boolean;
    /**
     *
     * @type {string}
     * @memberof GameserverBanStatusDto
     */
    bannedUntil: string;
}

export function GameserverBanStatusDtoFromJSON(json: any): GameserverBanStatusDto {
    return GameserverBanStatusDtoFromJSONTyped(json, false);
}

export function GameserverBanStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverBanStatusDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'status': GameserverBanReasonFromJSON(json['status']),
        'steam_id': json['steam_id'],
        'isBanned': json['isBanned'],
        'bannedUntil': json['bannedUntil'],
    };
}

export function GameserverBanStatusDtoToJSON(value?: GameserverBanStatusDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'status': GameserverBanReasonToJSON(value.status),
        'steam_id': value.steam_id,
        'isBanned': value.isBanned,
        'bannedUntil': value.bannedUntil,
    };
}


