/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GameserverPlayerAspect,
    GameserverPlayerAspectFromJSON,
    GameserverPlayerAspectFromJSONTyped,
    GameserverPlayerAspectToJSON,
} from './';

/**
 * 
 * @export
 * @interface GameserverPlayerAspectCountDto
 */
export class GameserverPlayerAspectCountDto {
    /**
     * 
     * @type {GameserverPlayerAspect}
     * @memberof GameserverPlayerAspectCountDto
     */
    aspect: GameserverPlayerAspect;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerAspectCountDto
     */
    count: number;
}

export function GameserverPlayerAspectCountDtoFromJSON(json: any): GameserverPlayerAspectCountDto {
    return GameserverPlayerAspectCountDtoFromJSONTyped(json, false);
}

export function GameserverPlayerAspectCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverPlayerAspectCountDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aspect': GameserverPlayerAspectFromJSON(json['aspect']),
        'count': json['count'],
    };
}

export function GameserverPlayerAspectCountDtoToJSON(value?: GameserverPlayerAspectCountDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aspect': GameserverPlayerAspectToJSON(value.aspect),
        'count': value.count,
    };
}


