// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GameserverPlayerTeammateDto } from './gameserver-player-teammate-dto';

/**
 * 
 * @export
 * @interface GameserverPlayerTeammatePage
 */
export interface GameserverPlayerTeammatePage {
    /**
     * 
     * @type {Array<GameserverPlayerTeammateDto>}
     * @memberof GameserverPlayerTeammatePage
     */
    data: Array<GameserverPlayerTeammateDto>;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerTeammatePage
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerTeammatePage
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerTeammatePage
     */
    pages: number;
}


