/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GameserverReportedMatrixDto
 */
export class GameserverReportedMatrixDto {
    /**
     *
     * @type {string}
     * @memberof GameserverReportedMatrixDto
     */
    steamId: string;
    /**
     *
     * @type {Array<string>}
     * @memberof GameserverReportedMatrixDto
     */
    reported: Array<string>;
}

export function GameserverReportedMatrixDtoFromJSON(json: any): GameserverReportedMatrixDto {
    return GameserverReportedMatrixDtoFromJSONTyped(json, false);
}

export function GameserverReportedMatrixDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverReportedMatrixDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'steamId': json['steamId'],
        'reported': json['reported'],
    };
}

export function GameserverReportedMatrixDtoToJSON(value?: GameserverReportedMatrixDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'steamId': value.steamId,
        'reported': value.reported,
    };
}


