/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GameserverGameServerDto
 */
export class GameserverGameServerDto {
    /**
     *
     * @type {string}
     * @memberof GameserverGameServerDto
     */
    url: string;
    /**
     *
     * @type {string}
     * @memberof GameserverGameServerDto
     */
    version: GameserverGameServerDtoVersionEnum;
}

export function GameserverGameServerDtoFromJSON(json: any): GameserverGameServerDto {
    return GameserverGameServerDtoFromJSONTyped(json, false);
}

export function GameserverGameServerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverGameServerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'url': json['url'],
        'version': json['version'],
    };
}

export function GameserverGameServerDtoToJSON(value?: GameserverGameServerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'url': value.url,
        'version': value.version,
    };
}

/**
* @export
* @enum {string}
*/
export enum GameserverGameServerDtoVersionEnum {
    _681 = 'Dota_681',
    _684 = 'Dota_684'
}


