/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GameserverItemDto
 */
export class GameserverItemDto {
    /**
     *
     * @type {number}
     * @memberof GameserverItemDto
     */
    item: number;
    /**
     *
     * @type {number}
     * @memberof GameserverItemDto
     */
    popularity: number;
    /**
     *
     * @type {number}
     * @memberof GameserverItemDto
     */
    games: number;
    /**
     *
     * @type {number}
     * @memberof GameserverItemDto
     */
    wins: number;
}

export function GameserverItemDtoFromJSON(json: any): GameserverItemDto {
    return GameserverItemDtoFromJSONTyped(json, false);
}

export function GameserverItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'item': json['item'],
        'popularity': json['popularity'],
        'games': json['games'],
        'wins': json['wins'],
    };
}

export function GameserverItemDtoToJSON(value?: GameserverItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'item': value.item,
        'popularity': value.popularity,
        'games': value.games,
        'wins': value.wins,
    };
}


