// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GameserverHeroStatsDto
 */
export interface GameserverHeroStatsDto {
    /**
     * 
     * @type {string}
     * @memberof GameserverHeroStatsDto
     */
    playerSteamId: string;
    /**
     * 
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    gpm: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    xpm: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    kda: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    games: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    loss: number;
    /**
     * 
     * @type {string}
     * @memberof GameserverHeroStatsDto
     */
    hero: string;
    /**
     * 
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    last_hits: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    denies: number;
}


