/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GameserverBanStatusDto
 */
export class GameserverBanStatusDto {
    /**
     *
     * @type {string}
     * @memberof GameserverBanStatusDto
     */
    steam_id: string;
    /**
     *
     * @type {boolean}
     * @memberof GameserverBanStatusDto
     */
    isBanned: boolean;
    /**
     *
     * @type {number}
     * @memberof GameserverBanStatusDto
     */
    bannedUntil: number;
    /**
     *
     * @type {number}
     * @memberof GameserverBanStatusDto
     */
    status: GameserverBanStatusDtoStatusEnum;
}

export function GameserverBanStatusDtoFromJSON(json: any): GameserverBanStatusDto {
    return GameserverBanStatusDtoFromJSONTyped(json, false);
}

export function GameserverBanStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverBanStatusDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'steam_id': json['steam_id'],
        'isBanned': json['isBanned'],
        'bannedUntil': json['bannedUntil'],
        'status': json['status'],
    };
}

export function GameserverBanStatusDtoToJSON(value?: GameserverBanStatusDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'steam_id': value.steam_id,
        'isBanned': value.isBanned,
        'bannedUntil': value.bannedUntil,
        'status': value.status,
    };
}

/**
* @export
* @enum {string}
*/
export enum GameserverBanStatusDtoStatusEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}


