/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameserverMatchDto, GameserverMatchDtoFromJSON, GameserverMatchDtoToJSON } from './';

/**
 *
 * @export
 * @interface GameserverMatchPageDto
 */
export class GameserverMatchPageDto {
    /**
     *
     * @type {Array<GameserverMatchDto>}
     * @memberof GameserverMatchPageDto
     */
    data: Array<GameserverMatchDto>;
    /**
     *
     * @type {number}
     * @memberof GameserverMatchPageDto
     */
    pages: number;
    /**
     *
     * @type {number}
     * @memberof GameserverMatchPageDto
     */
    perPage: number;
    /**
     *
     * @type {number}
     * @memberof GameserverMatchPageDto
     */
    page: number;
}

export function GameserverMatchPageDtoFromJSON(json: any): GameserverMatchPageDto {
    return GameserverMatchPageDtoFromJSONTyped(json, false);
}

export function GameserverMatchPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverMatchPageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'data': ((json['data'] as Array<any>).map(GameserverMatchDtoFromJSON)),
        'pages': json['pages'],
        'perPage': json['perPage'],
        'page': json['page'],
    };
}

export function GameserverMatchPageDtoToJSON(value?: GameserverMatchPageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'data': ((value.data as Array<any>).map(GameserverMatchDtoToJSON)),
        'pages': value.pages,
        'perPage': value.perPage,
        'page': value.page,
    };
}


