/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GameserverHeroStatsDto
 */
export class GameserverHeroStatsDto {
    /**
     *
     * @type {string}
     * @memberof GameserverHeroStatsDto
     */
    playerId: string;
    /**
     *
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    gpm: number;
    /**
     *
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    xpm: number;
    /**
     *
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    kda: number;
    /**
     *
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    games: number;
    /**
     *
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    wins: number;
    /**
     *
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    loss: number;
    /**
     *
     * @type {string}
     * @memberof GameserverHeroStatsDto
     */
    hero: string;
    /**
     *
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    last_hits: number;
    /**
     *
     * @type {number}
     * @memberof GameserverHeroStatsDto
     */
    denies: number;
}

export function GameserverHeroStatsDtoFromJSON(json: any): GameserverHeroStatsDto {
    return GameserverHeroStatsDtoFromJSONTyped(json, false);
}

export function GameserverHeroStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverHeroStatsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'playerId': json['playerId'],
        'gpm': json['gpm'],
        'xpm': json['xpm'],
        'kda': json['kda'],
        'games': json['games'],
        'wins': json['wins'],
        'loss': json['loss'],
        'hero': json['hero'],
        'last_hits': json['last_hits'],
        'denies': json['denies'],
    };
}

export function GameserverHeroStatsDtoToJSON(value?: GameserverHeroStatsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'playerId': value.playerId,
        'gpm': value.gpm,
        'xpm': value.xpm,
        'kda': value.kda,
        'games': value.games,
        'wins': value.wins,
        'loss': value.loss,
        'hero': value.hero,
        'last_hits': value.last_hits,
        'denies': value.denies,
    };
}


