/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GameserverCrimeLogDto,
    GameserverCrimeLogDtoFromJSON,
    GameserverCrimeLogDtoFromJSONTyped,
    GameserverCrimeLogDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface GameserverCrimeLogPageDto
 */
export class GameserverCrimeLogPageDto {
    /**
     * 
     * @type {Array<GameserverCrimeLogDto>}
     * @memberof GameserverCrimeLogPageDto
     */
    data: Array<GameserverCrimeLogDto>;
    /**
     * 
     * @type {number}
     * @memberof GameserverCrimeLogPageDto
     */
    pages: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverCrimeLogPageDto
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverCrimeLogPageDto
     */
    page: number;
}

export function GameserverCrimeLogPageDtoFromJSON(json: any): GameserverCrimeLogPageDto {
    return GameserverCrimeLogPageDtoFromJSONTyped(json, false);
}

export function GameserverCrimeLogPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverCrimeLogPageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GameserverCrimeLogDtoFromJSON)),
        'pages': json['pages'],
        'perPage': json['perPage'],
        'page': json['page'],
    };
}

export function GameserverCrimeLogPageDtoToJSON(value?: GameserverCrimeLogPageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GameserverCrimeLogDtoToJSON)),
        'pages': value.pages,
        'perPage': value.perPage,
        'page': value.page,
    };
}


