/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GameserverAggregatedStatsDto
 */
export class GameserverAggregatedStatsDto {
    /**
     *
     * @type {number}
     * @memberof GameserverAggregatedStatsDto
     */
    playersYesterday: number;
    /**
     *
     * @type {number}
     * @memberof GameserverAggregatedStatsDto
     */
    playersWeekly: number;
    /**
     *
     * @type {number}
     * @memberof GameserverAggregatedStatsDto
     */
    humanGamesWeekly: number;
}

export function GameserverAggregatedStatsDtoFromJSON(json: any): GameserverAggregatedStatsDto {
    return GameserverAggregatedStatsDtoFromJSONTyped(json, false);
}

export function GameserverAggregatedStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverAggregatedStatsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'playersYesterday': json['playersYesterday'],
        'playersWeekly': json['playersWeekly'],
        'humanGamesWeekly': json['humanGamesWeekly'],
    };
}

export function GameserverAggregatedStatsDtoToJSON(value?: GameserverAggregatedStatsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'playersYesterday': value.playersYesterday,
        'playersWeekly': value.playersWeekly,
        'humanGamesWeekly': value.humanGamesWeekly,
    };
}


