// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GameserverGameServerDto
 */
export interface GameserverGameServerDto {
    /**
     * 
     * @type {string}
     * @memberof GameserverGameServerDto
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GameserverGameServerDto
     */
    version: GameserverGameServerDtoVersionEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum GameserverGameServerDtoVersionEnum {
    _681 = 'Dota_681',
    _684 = 'Dota_684'
}



