/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  GameserverReportedMatrixDto,
  GameserverReportedMatrixDtoFromJSON,
  GameserverReportedMatrixDtoToJSON,
} from './';

/**
 *
 * @export
 * @interface GameserverMatchReportMatrixDto
 */
export class GameserverMatchReportMatrixDto {
    /**
     *
     * @type {number}
     * @memberof GameserverMatchReportMatrixDto
     */
    matchId: number;
    /**
     *
     * @type {string}
     * @memberof GameserverMatchReportMatrixDto
     */
    timestamp: string;
    /**
     *
     * @type {Array<GameserverReportedMatrixDto>}
     * @memberof GameserverMatchReportMatrixDto
     */
    reports: Array<GameserverReportedMatrixDto>;
}

export function GameserverMatchReportMatrixDtoFromJSON(json: any): GameserverMatchReportMatrixDto {
    return GameserverMatchReportMatrixDtoFromJSONTyped(json, false);
}

export function GameserverMatchReportMatrixDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverMatchReportMatrixDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'matchId': json['matchId'],
        'timestamp': json['timestamp'],
        'reports': ((json['reports'] as Array<any>).map(GameserverReportedMatrixDtoFromJSON)),
    };
}

export function GameserverMatchReportMatrixDtoToJSON(value?: GameserverMatchReportMatrixDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'matchId': value.matchId,
        'timestamp': value.timestamp,
        'reports': ((value.reports as Array<any>).map(GameserverReportedMatrixDtoToJSON)),
    };
}


