// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GameserverMatchDto } from './gameserver-match-dto';

/**
 * 
 * @export
 * @interface GameserverMatchPageDto
 */
export interface GameserverMatchPageDto {
    /**
     * 
     * @type {Array<GameserverMatchDto>}
     * @memberof GameserverMatchPageDto
     */
    data: Array<GameserverMatchDto>;
    /**
     * 
     * @type {number}
     * @memberof GameserverMatchPageDto
     */
    pages: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverMatchPageDto
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverMatchPageDto
     */
    page: number;
}


