// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GameserverPlayerInMatchDto
 */
export interface GameserverPlayerInMatchDto {
    /**
     * 
     * @type {string}
     * @memberof GameserverPlayerInMatchDto
     */
    steam_id: string;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    team: number;
    /**
     * 
     * @type {string}
     * @memberof GameserverPlayerInMatchDto
     */
    hero: string;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    level: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    kills: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    deaths: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    assists: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    gpm: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    xpm: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    last_hits: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerInMatchDto
     */
    denies: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameserverPlayerInMatchDto
     */
    items: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof GameserverPlayerInMatchDto
     */
    abandoned: boolean;
}


