/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GameserverMatchInfoDto,
    GameserverMatchInfoDtoFromJSON,
    GameserverMatchInfoDtoFromJSONTyped,
    GameserverMatchInfoDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface GameserverGameSessionDto
 */
export class GameserverGameSessionDto {
    /**
     * 
     * @type {string}
     * @memberof GameserverGameSessionDto
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof GameserverGameSessionDto
     */
    matchId: number;
    /**
     * 
     * @type {GameserverMatchInfoDto}
     * @memberof GameserverGameSessionDto
     */
    info: GameserverMatchInfoDto;
}

export function GameserverGameSessionDtoFromJSON(json: any): GameserverGameSessionDto {
    return GameserverGameSessionDtoFromJSONTyped(json, false);
}

export function GameserverGameSessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverGameSessionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'matchId': json['matchId'],
        'info': GameserverMatchInfoDtoFromJSON(json['info']),
    };
}

export function GameserverGameSessionDtoToJSON(value?: GameserverGameSessionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'matchId': value.matchId,
        'info': GameserverMatchInfoDtoToJSON(value.info),
    };
}


