// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GameserverBanStatusDto
 */
export interface GameserverBanStatusDto {
    /**
     * 
     * @type {string}
     * @memberof GameserverBanStatusDto
     */
    steam_id: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameserverBanStatusDto
     */
    isBanned: boolean;
    /**
     * 
     * @type {number}
     * @memberof GameserverBanStatusDto
     */
    bannedUntil: number;
    /**
     * 
     * @type {string}
     * @memberof GameserverBanStatusDto
     */
    status: GameserverBanStatusDtoStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum GameserverBanStatusDtoStatusEnum {
    GAMEDECLINE = 'GAME_DECLINE',
    LOADFAILURE = 'LOAD_FAILURE',
    INFINITEBAN = 'INFINITE_BAN'
}



