/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GameserverMatchmakingMode,
    GameserverMatchmakingModeFromJSON,
    GameserverMatchmakingModeFromJSONTyped,
    GameserverMatchmakingModeToJSON,
} from './';

/**
 * 
 * @export
 * @interface GameserverPlayerYearSummaryDto
 */
export class GameserverPlayerYearSummaryDto {
    /**
     * 
     * @type {GameserverMatchmakingMode}
     * @memberof GameserverPlayerYearSummaryDto
     */
    most_played_mode: GameserverMatchmakingMode;
    /**
     * 
     * @type {string}
     * @memberof GameserverPlayerYearSummaryDto
     */
    steam_id: string;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    last_hits: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    denies: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    gold: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    support_gold: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    kills: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    deaths: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    assists: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    misses: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    kda: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    played_games: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    most_played_mode_count: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    most_purchased_item: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverPlayerYearSummaryDto
     */
    most_purchased_item_count: number;
}

export function GameserverPlayerYearSummaryDtoFromJSON(json: any): GameserverPlayerYearSummaryDto {
    return GameserverPlayerYearSummaryDtoFromJSONTyped(json, false);
}

export function GameserverPlayerYearSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverPlayerYearSummaryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'most_played_mode': GameserverMatchmakingModeFromJSON(json['most_played_mode']),
        'steam_id': json['steam_id'],
        'last_hits': json['last_hits'],
        'denies': json['denies'],
        'gold': json['gold'],
        'support_gold': json['support_gold'],
        'kills': json['kills'],
        'deaths': json['deaths'],
        'assists': json['assists'],
        'misses': json['misses'],
        'kda': json['kda'],
        'played_games': json['played_games'],
        'most_played_mode_count': json['most_played_mode_count'],
        'most_purchased_item': json['most_purchased_item'],
        'most_purchased_item_count': json['most_purchased_item_count'],
    };
}

export function GameserverPlayerYearSummaryDtoToJSON(value?: GameserverPlayerYearSummaryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'most_played_mode': GameserverMatchmakingModeToJSON(value.most_played_mode),
        'steam_id': value.steam_id,
        'last_hits': value.last_hits,
        'denies': value.denies,
        'gold': value.gold,
        'support_gold': value.support_gold,
        'kills': value.kills,
        'deaths': value.deaths,
        'assists': value.assists,
        'misses': value.misses,
        'kda': value.kda,
        'played_games': value.played_games,
        'most_played_mode_count': value.most_played_mode_count,
        'most_purchased_item': value.most_purchased_item,
        'most_purchased_item_count': value.most_purchased_item_count,
    };
}


