/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GameserverPlayerDailyRecord
 */
export class GameserverPlayerDailyRecord {
    /**
     *
     * @type {string}
     * @memberof GameserverPlayerDailyRecord
     */
    steam_id: string;
    /**
     *
     * @type {number}
     * @memberof GameserverPlayerDailyRecord
     */
    mmr_change: number;
    /**
     *
     * @type {number}
     * @memberof GameserverPlayerDailyRecord
     */
    games: number;
    /**
     *
     * @type {number}
     * @memberof GameserverPlayerDailyRecord
     */
    wins: number;
    /**
     *
     * @type {number}
     * @memberof GameserverPlayerDailyRecord
     */
    loss: number;
}

export function GameserverPlayerDailyRecordFromJSON(json: any): GameserverPlayerDailyRecord {
    return GameserverPlayerDailyRecordFromJSONTyped(json, false);
}

export function GameserverPlayerDailyRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverPlayerDailyRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'steam_id': json['steam_id'],
        'mmr_change': json['mmr_change'],
        'games': json['games'],
        'wins': json['wins'],
        'loss': json['loss'],
    };
}

export function GameserverPlayerDailyRecordToJSON(value?: GameserverPlayerDailyRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'steam_id': value.steam_id,
        'mmr_change': value.mmr_change,
        'games': value.games,
        'wins': value.wins,
        'loss': value.loss,
    };
}


