// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GameserverLeaderboardEntryDto
 */
export interface GameserverLeaderboardEntryDto {
    /**
     * 
     * @type {string}
     * @memberof GameserverLeaderboardEntryDto
     */
    steam_id: string;
    /**
     * 
     * @type {number}
     * @memberof GameserverLeaderboardEntryDto
     */
    mmr: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverLeaderboardEntryDto
     */
    games: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverLeaderboardEntryDto
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverLeaderboardEntryDto
     */
    kills: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverLeaderboardEntryDto
     */
    deaths: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverLeaderboardEntryDto
     */
    assists: number;
    /**
     * 
     * @type {number}
     * @memberof GameserverLeaderboardEntryDto
     */
    play_time: number;
}


