/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameserverDotaGameMode, GameserverDotaGameModeFromJSON, GameserverDotaGameModeToJSON } from './';

/**
 *
 * @export
 * @interface GameserverUpdateGamemodeDto
 */
export class GameserverUpdateGamemodeDto {
    /**
     *
     * @type {GameserverDotaGameMode}
     * @memberof GameserverUpdateGamemodeDto
     */
    game_mode: GameserverDotaGameMode;
    /**
     *
     * @type {boolean}
     * @memberof GameserverUpdateGamemodeDto
     */
    enabled: boolean;
}

export function GameserverUpdateGamemodeDtoFromJSON(json: any): GameserverUpdateGamemodeDto {
    return GameserverUpdateGamemodeDtoFromJSONTyped(json, false);
}

export function GameserverUpdateGamemodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverUpdateGamemodeDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'game_mode': GameserverDotaGameModeFromJSON(json['game_mode']),
        'enabled': json['enabled'],
    };
}

export function GameserverUpdateGamemodeDtoToJSON(value?: GameserverUpdateGamemodeDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'game_mode': GameserverDotaGameModeToJSON(value.game_mode),
        'enabled': value.enabled,
    };
}


