/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  GameserverDotaGameMode,
  GameserverDotaGameModeFromJSON,
  GameserverDotaGameModeToJSON,
  GameserverMatchmakingMode,
  GameserverMatchmakingModeFromJSON,
  GameserverMatchmakingModeToJSON,
} from './';

/**
 *
 * @export
 * @interface GameserverMatchmakingModeInfoDto
 */
export class GameserverMatchmakingModeInfoDto {
    /**
     *
     * @type {GameserverMatchmakingMode}
     * @memberof GameserverMatchmakingModeInfoDto
     */
    lobby_type: GameserverMatchmakingMode;
    /**
     *
     * @type {GameserverDotaGameMode}
     * @memberof GameserverMatchmakingModeInfoDto
     */
    game_mode: GameserverDotaGameMode;
    /**
     *
     * @type {boolean}
     * @memberof GameserverMatchmakingModeInfoDto
     */
    enabled: boolean;
}

export function GameserverMatchmakingModeInfoDtoFromJSON(json: any): GameserverMatchmakingModeInfoDto {
    return GameserverMatchmakingModeInfoDtoFromJSONTyped(json, false);
}

export function GameserverMatchmakingModeInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameserverMatchmakingModeInfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'lobby_type': GameserverMatchmakingModeFromJSON(json['lobby_type']),
        'game_mode': GameserverDotaGameModeFromJSON(json['game_mode']),
        'enabled': json['enabled'],
    };
}

export function GameserverMatchmakingModeInfoDtoToJSON(value?: GameserverMatchmakingModeInfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'lobby_type': GameserverMatchmakingModeToJSON(value.lobby_type),
        'game_mode': GameserverDotaGameModeToJSON(value.game_mode),
        'enabled': value.enabled,
    };
}


