/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ForumCreateThreadDTO
 */
export class ForumCreateThreadDTO {
    /**
     *
     * @type {string}
     * @memberof ForumCreateThreadDTO
     */
    externalKey: string;
}

export function ForumCreateThreadDTOFromJSON(json: any): ForumCreateThreadDTO {
    return ForumCreateThreadDTOFromJSONTyped(json, false);
}

export function ForumCreateThreadDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumCreateThreadDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'externalKey': json['externalKey'],
    };
}

export function ForumCreateThreadDTOToJSON(value?: ForumCreateThreadDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'externalKey': value.externalKey,
    };
}


