/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ForumThreadDTO
 */
export class ForumThreadDTO {
    /**
     *
     * @type {string}
     * @memberof ForumThreadDTO
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ForumThreadDTO
     */
    external_id: string;
}

export function ForumThreadDTOFromJSON(json: any): ForumThreadDTO {
    return ForumThreadDTOFromJSONTyped(json, false);
}

export function ForumThreadDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumThreadDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'external_id': json['external_id'],
    };
}

export function ForumThreadDTOToJSON(value?: ForumThreadDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'external_id': value.external_id,
    };
}


