/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';


/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    prometheusControllerIndexContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/metrics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    prometheusControllerIndex = async (): Promise<void> => {
        await this.prometheusControllerIndexRaw();
    }

    /**
     */
    private async prometheusControllerIndexRaw(): Promise<runtime.ApiResponse<void>> {
        this.prometheusControllerIndexValidation();
        const context = this.prometheusControllerIndexContext();
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    private prometheusControllerIndexValidation() {
    }

}
