/* tslint:disable */
/* eslint-disable */

/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MatchmakingMode as M2 } from '../../gateway/shared-types/matchmaking-mode';

/**
 *
 * @export
 * @enum {string}
 */
// export type MatchmakingMode =

export { M2 as MatchmakingMode };

export function MatchmakingModeFromJSON(json: any): M2 {
  return MatchmakingModeFromJSONTyped(json, false);
}

export function MatchmakingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): M2 {
  return json as M2;
}

export function MatchmakingModeToJSON(value?: M2 | null): any {
  return value as any;
}

