/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeBotDropItemDto
 */
export class TradeBotDropItemDto {
    /**
     * 
     * @type {number}
     * @memberof TradeBotDropItemDto
     */
    tierId: number;
}

export function TradeBotDropItemDtoFromJSON(json: any): TradeBotDropItemDto {
    return TradeBotDropItemDtoFromJSONTyped(json, false);
}

export function TradeBotDropItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotDropItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tierId': json['tierId'],
    };
}

export function TradeBotDropItemDtoToJSON(value?: TradeBotDropItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tierId': value.tierId,
    };
}


