/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TradeBotItemQuality {
    Standard = 'Standard',
    Inscribed = 'Inscribed',
    Auspicious = 'Auspicious',
    Genuine = 'Genuine',
    Autographed = 'Autographed',
    Heroic = 'Heroic',
    Frozen = 'Frozen',
    Base = 'Base',
    Cursed = 'Cursed',
    Unusual = 'Unusual',
    Infused = 'Infused',
    Corrupted = 'Corrupted',
    Exalted = 'Exalted',
    Elder = 'Elder',
    Glitter = 'Glitter',
    Gold = 'Gold',
    Holo = 'Holo',
    Legacy = 'Legacy',
    Favored = 'Favored',
    Ascendant = 'Ascendant'
}

export function TradeBotItemQualityFromJSON(json: any): TradeBotItemQuality {
    return TradeBotItemQualityFromJSONTyped(json, false);
}

export function TradeBotItemQualityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotItemQuality {
    return json as TradeBotItemQuality;
}

export function TradeBotItemQualityToJSON(value?: TradeBotItemQuality | null): any {
    return value as any;
}

