/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeBotUpdateDropSettingsDto
 */
export class TradeBotUpdateDropSettingsDto {
    /**
     * 
     * @type {number}
     * @memberof TradeBotUpdateDropSettingsDto
     */
    baseDropChance?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeBotUpdateDropSettingsDto
     */
    subsequentDropChance?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeBotUpdateDropSettingsDto
     */
    desiredStock?: number;
}

export function TradeBotUpdateDropSettingsDtoFromJSON(json: any): TradeBotUpdateDropSettingsDto {
    return TradeBotUpdateDropSettingsDtoFromJSONTyped(json, false);
}

export function TradeBotUpdateDropSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotUpdateDropSettingsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'baseDropChance': !exists(json, 'baseDropChance') ? undefined : json['baseDropChance'],
        'subsequentDropChance': !exists(json, 'subsequentDropChance') ? undefined : json['subsequentDropChance'],
        'desiredStock': !exists(json, 'desiredStock') ? undefined : json['desiredStock'],
    };
}

export function TradeBotUpdateDropSettingsDtoToJSON(value?: TradeBotUpdateDropSettingsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'baseDropChance': value.baseDropChance,
        'subsequentDropChance': value.subsequentDropChance,
        'desiredStock': value.desiredStock,
    };
}


