/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TradeBotUpdateUserDto
 */
export class TradeBotUpdateUserDto {
    /**
     *
     * @type {string}
     * @memberof TradeBotUpdateUserDto
     */
    tradeLink: string;
}

export function TradeBotUpdateUserDtoFromJSON(json: any): TradeBotUpdateUserDto {
    return TradeBotUpdateUserDtoFromJSONTyped(json, false);
}

export function TradeBotUpdateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotUpdateUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'tradeLink': json['tradeLink'],
    };
}

export function TradeBotUpdateUserDtoToJSON(value?: TradeBotUpdateUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'tradeLink': value.tradeLink,
    };
}


