/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeBotPurchaseDto
 */
export class TradeBotPurchaseDto {
    /**
     * 
     * @type {number}
     * @memberof TradeBotPurchaseDto
     */
    amount: number;
}

export function TradeBotPurchaseDtoFromJSON(json: any): TradeBotPurchaseDto {
    return TradeBotPurchaseDtoFromJSONTyped(json, false);
}

export function TradeBotPurchaseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotPurchaseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function TradeBotPurchaseDtoToJSON(value?: TradeBotPurchaseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
    };
}


