/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TradeBotCreateDropTierDto
 */
export class TradeBotCreateDropTierDto {
    /**
     *
     * @type {number}
     * @memberof TradeBotCreateDropTierDto
     */
    minPrice: number;
    /**
     *
     * @type {number}
     * @memberof TradeBotCreateDropTierDto
     */
    maxPrice: number;
    /**
     *
     * @type {number}
     * @memberof TradeBotCreateDropTierDto
     */
    weight: number;
}

export function TradeBotCreateDropTierDtoFromJSON(json: any): TradeBotCreateDropTierDto {
    return TradeBotCreateDropTierDtoFromJSONTyped(json, false);
}

export function TradeBotCreateDropTierDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotCreateDropTierDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'minPrice': json['minPrice'],
        'maxPrice': json['maxPrice'],
        'weight': json['weight'],
    };
}

export function TradeBotCreateDropTierDtoToJSON(value?: TradeBotCreateDropTierDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'minPrice': value.minPrice,
        'maxPrice': value.maxPrice,
        'weight': value.weight,
    };
}


