/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TradeBotItemQuality, TradeBotItemQualityFromJSON, TradeBotItemQualityToJSON } from './';

/**
 *
 * @export
 * @interface TradeBotMarketItemDto
 */
export class TradeBotMarketItemDto {
    /**
     *
     * @type {TradeBotItemQuality}
     * @memberof TradeBotMarketItemDto
     */
    quality: TradeBotItemQuality;
    /**
     *
     * @type {string}
     * @memberof TradeBotMarketItemDto
     */
    marketHashName: string;
    /**
     *
     * @type {number}
     * @memberof TradeBotMarketItemDto
     */
    price: number;
    /**
     *
     * @type {string}
     * @memberof TradeBotMarketItemDto
     */
    icon: string;
}

export function TradeBotMarketItemDtoFromJSON(json: any): TradeBotMarketItemDto {
    return TradeBotMarketItemDtoFromJSONTyped(json, false);
}

export function TradeBotMarketItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotMarketItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'quality': TradeBotItemQualityFromJSON(json['quality']),
        'marketHashName': json['marketHashName'],
        'price': json['price'],
        'icon': json['icon'],
    };
}

export function TradeBotMarketItemDtoToJSON(value?: TradeBotMarketItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'quality': TradeBotItemQualityToJSON(value.quality),
        'marketHashName': value.marketHashName,
        'price': value.price,
        'icon': value.icon,
    };
}


