/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeBotTradeOfferDto
 */
export class TradeBotTradeOfferDto {
    /**
     * 
     * @type {string}
     * @memberof TradeBotTradeOfferDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof TradeBotTradeOfferDto
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof TradeBotTradeOfferDto
     */
    itemCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof TradeBotTradeOfferDto
     */
    incoming: boolean;
    /**
     * 
     * @type {string}
     * @memberof TradeBotTradeOfferDto
     */
    createdAt: string;
}

export function TradeBotTradeOfferDtoFromJSON(json: any): TradeBotTradeOfferDto {
    return TradeBotTradeOfferDtoFromJSONTyped(json, false);
}

export function TradeBotTradeOfferDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotTradeOfferDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'itemCount': json['itemCount'],
        'incoming': json['incoming'],
        'createdAt': json['createdAt'],
    };
}

export function TradeBotTradeOfferDtoToJSON(value?: TradeBotTradeOfferDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'amount': value.amount,
        'itemCount': value.itemCount,
        'incoming': value.incoming,
        'createdAt': value.createdAt,
    };
}


