/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeBotUserDto
 */
export class TradeBotUserDto {
    /**
     * 
     * @type {string}
     * @memberof TradeBotUserDto
     */
    steamId: string;
    /**
     * 
     * @type {number}
     * @memberof TradeBotUserDto
     */
    balance: number;
    /**
     * 
     * @type {string}
     * @memberof TradeBotUserDto
     */
    tradeLink: string;
}

export function TradeBotUserDtoFromJSON(json: any): TradeBotUserDto {
    return TradeBotUserDtoFromJSONTyped(json, false);
}

export function TradeBotUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'steamId': json['steamId'],
        'balance': json['balance'],
        'tradeLink': json['tradeLink'],
    };
}

export function TradeBotUserDtoToJSON(value?: TradeBotUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'steamId': value.steamId,
        'balance': value.balance,
        'tradeLink': value.tradeLink,
    };
}


