/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeBotUpdateDropTierDto
 */
export class TradeBotUpdateDropTierDto {
    /**
     * 
     * @type {number}
     * @memberof TradeBotUpdateDropTierDto
     */
    minPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeBotUpdateDropTierDto
     */
    maxPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof TradeBotUpdateDropTierDto
     */
    weight?: number;
}

export function TradeBotUpdateDropTierDtoFromJSON(json: any): TradeBotUpdateDropTierDto {
    return TradeBotUpdateDropTierDtoFromJSONTyped(json, false);
}

export function TradeBotUpdateDropTierDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotUpdateDropTierDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minPrice': !exists(json, 'minPrice') ? undefined : json['minPrice'],
        'maxPrice': !exists(json, 'maxPrice') ? undefined : json['maxPrice'],
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
    };
}

export function TradeBotUpdateDropTierDtoToJSON(value?: TradeBotUpdateDropTierDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'minPrice': value.minPrice,
        'maxPrice': value.maxPrice,
        'weight': value.weight,
    };
}


