/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TradeBotDropSettingsDto
 */
export class TradeBotDropSettingsDto {
    /**
     *
     * @type {number}
     * @memberof TradeBotDropSettingsDto
     */
    baseDropChance: number;
    /**
     *
     * @type {number}
     * @memberof TradeBotDropSettingsDto
     */
    subsequentDropChance: number;
    /**
     *
     * @type {number}
     * @memberof TradeBotDropSettingsDto
     */
    desiredStock: number;
}

export function TradeBotDropSettingsDtoFromJSON(json: any): TradeBotDropSettingsDto {
    return TradeBotDropSettingsDtoFromJSONTyped(json, false);
}

export function TradeBotDropSettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotDropSettingsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'baseDropChance': json['baseDropChance'],
        'subsequentDropChance': json['subsequentDropChance'],
        'desiredStock': json['desiredStock'],
    };
}

export function TradeBotDropSettingsDtoToJSON(value?: TradeBotDropSettingsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'baseDropChance': value.baseDropChance,
        'subsequentDropChance': value.subsequentDropChance,
        'desiredStock': value.desiredStock,
    };
}


