/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeBotDropTierDto
 */
export class TradeBotDropTierDto {
    /**
     * 
     * @type {number}
     * @memberof TradeBotDropTierDto
     */
    minPrice: number;
    /**
     * 
     * @type {number}
     * @memberof TradeBotDropTierDto
     */
    maxPrice: number;
    /**
     * 
     * @type {number}
     * @memberof TradeBotDropTierDto
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TradeBotDropTierDto
     */
    weight: number;
}

export function TradeBotDropTierDtoFromJSON(json: any): TradeBotDropTierDto {
    return TradeBotDropTierDtoFromJSONTyped(json, false);
}

export function TradeBotDropTierDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeBotDropTierDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minPrice': json['minPrice'],
        'maxPrice': json['maxPrice'],
        'id': json['id'],
        'weight': json['weight'],
    };
}

export function TradeBotDropTierDtoToJSON(value?: TradeBotDropTierDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'minPrice': value.minPrice,
        'maxPrice': value.maxPrice,
        'id': value.id,
        'weight': value.weight,
    };
}


