// tslint:disable
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosInstance, AxiosPromise } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError } from '../base';
// @ts-ignore
// @ts-ignore
import { GameserverHeroItemDto, GameserverHeroSummaryDto } from '../models';

/**
 * MetaApi - axios parameter creator
 * @export
 */
export const MetaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @param {string} hero
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        metaControllerHeroData: async (hero: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'hero' is not null or undefined
            if (hero === null || hero === undefined) {
                throw new RequiredError('hero','Required parameter hero was null or undefined when calling metaControllerHeroData.');
            }
            const localVarPath = `/meta/heroes/{hero}`
                .replace(`{${"hero"}}`, encodeURIComponent(String(hero)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        metaControllerHeroes: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/meta/heroes`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetaApi - functional programming interface
 * @export
 */
export const MetaApiFp = function(configuration?: Configuration) {
    return {
        /**
         *
         * @param {string} hero
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async metaControllerHeroData(hero: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GameserverHeroItemDto>>> {
            const localVarAxiosArgs = await MetaApiAxiosParamCreator(configuration).metaControllerHeroData(hero, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async metaControllerHeroes(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GameserverHeroSummaryDto>>> {
            const localVarAxiosArgs = await MetaApiAxiosParamCreator(configuration).metaControllerHeroes(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetaApi - factory interface
 * @export
 */
export const MetaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         *
         * @param {string} hero
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        metaControllerHeroData(hero: string, options?: any): AxiosPromise<Array<GameserverHeroItemDto>> {
            return MetaApiFp(configuration).metaControllerHeroData(hero, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        metaControllerHeroes(options?: any): AxiosPromise<Array<GameserverHeroSummaryDto>> {
            return MetaApiFp(configuration).metaControllerHeroes(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetaApi - object-oriented interface
 * @export
 * @class MetaApi
 * @extends {BaseAPI}
 */
export class MetaApi extends BaseAPI {
    /**
     *
     * @param {string} hero
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetaApi
     */
    public metaControllerHeroData(hero: string, options?: any) {
        return MetaApiFp(this.configuration).metaControllerHeroData(hero, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetaApi
     */
    public metaControllerHeroes(options?: any) {
        return MetaApiFp(this.configuration).metaControllerHeroes(options).then((request) => request(this.axios, this.basePath));
    }

}
