/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import { TournamentBracketType, TournamentBracketTypeFromJSON, TournamentBracketTypeToJSON } from './';

/**
 *
 * @export
 * @interface TournamentUpdateTournamentDto
 */
export class TournamentUpdateTournamentDto {
    /**
     *
     * @type {TournamentBracketType}
     * @memberof TournamentUpdateTournamentDto
     */
    strategy?: TournamentBracketType;
    /**
     *
     * @type {string}
     * @memberof TournamentUpdateTournamentDto
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof TournamentUpdateTournamentDto
     */
    description?: string;
    /**
     *
     * @type {number}
     * @memberof TournamentUpdateTournamentDto
     */
    teamSize?: number;
    /**
     *
     * @type {Date}
     * @memberof TournamentUpdateTournamentDto
     */
    startDate?: Date;
    /**
     *
     * @type {string}
     * @memberof TournamentUpdateTournamentDto
     */
    imageUrl?: string;
    /**
     *
     * @type {number}
     * @memberof TournamentUpdateTournamentDto
     */
    roundBestOf?: number;
    /**
     *
     * @type {number}
     * @memberof TournamentUpdateTournamentDto
     */
    finalBestOf?: number;
    /**
     *
     * @type {number}
     * @memberof TournamentUpdateTournamentDto
     */
    grandFinalBestOf?: number;
}

export function TournamentUpdateTournamentDtoFromJSON(json: any): TournamentUpdateTournamentDto {
    return TournamentUpdateTournamentDtoFromJSONTyped(json, false);
}

export function TournamentUpdateTournamentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentUpdateTournamentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'strategy': !exists(json, 'strategy') ? undefined : TournamentBracketTypeFromJSON(json['strategy']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'teamSize': !exists(json, 'teamSize') ? undefined : json['teamSize'],
        'startDate': !exists(json, 'startDate') ? undefined : (new Date(json['startDate'])),
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'roundBestOf': !exists(json, 'roundBestOf') ? undefined : json['roundBestOf'],
        'finalBestOf': !exists(json, 'finalBestOf') ? undefined : json['finalBestOf'],
        'grandFinalBestOf': !exists(json, 'grandFinalBestOf') ? undefined : json['grandFinalBestOf'],
    };
}

export function TournamentUpdateTournamentDtoToJSON(value?: TournamentUpdateTournamentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'strategy': TournamentBracketTypeToJSON(value.strategy),
        'name': value.name,
        'description': value.description,
        'teamSize': value.teamSize,
        'startDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'imageUrl': value.imageUrl,
        'roundBestOf': value.roundBestOf,
        'finalBestOf': value.finalBestOf,
        'grandFinalBestOf': value.grandFinalBestOf,
    };
}


