// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TournamentTeamDto } from './tournament-team-dto';

/**
 *
 * @export
 * @interface TournamentSeedItemDto
 */
export interface TournamentSeedItemDto {
  /**
   *
   * @type {string}
   * @memberof TournamentSeedItemDto
   */
  steam_id?: string;
  /**
   *
   * @type {string}
   * @memberof TournamentSeedItemDto
   */
  result?: string;
  /**
   *
   * @type {TournamentTeamDto}
   * @memberof TournamentSeedItemDto
   */
  team?: TournamentTeamDto;
  /**
   *
   * @type {boolean}
   * @memberof TournamentSeedItemDto
   */
  tbd?: boolean;
  /**
   *
   * @type {number}
   * @memberof TournamentSeedItemDto
   */
  score?: number;
}
