/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentScheduleTournamentGameDto
 */
export class TournamentScheduleTournamentGameDto {
    /**
     *
     * @type {string}
     * @memberof TournamentScheduleTournamentGameDto
     */
    gameId: string;
    /**
     *
     * @type {string}
     * @memberof TournamentScheduleTournamentGameDto
     */
    scheduledDate: string;
}

export function TournamentScheduleTournamentGameDtoFromJSON(json: any): TournamentScheduleTournamentGameDto {
    return TournamentScheduleTournamentGameDtoFromJSONTyped(json, false);
}

export function TournamentScheduleTournamentGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentScheduleTournamentGameDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'gameId': json['gameId'],
        'scheduledDate': json['scheduledDate'],
    };
}

export function TournamentScheduleTournamentGameDtoToJSON(value?: TournamentScheduleTournamentGameDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'gameId': value.gameId,
        'scheduledDate': value.scheduledDate,
    };
}


