/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentStageDto
 */
export class TournamentStageDto {
    /**
     * 
     * @type {number}
     * @memberof TournamentStageDto
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentStageDto
     */
    tournament_id: number;
    /**
     * 
     * @type {string}
     * @memberof TournamentStageDto
     */
    name: string;
    /**
     * 
     * @type {object}
     * @memberof TournamentStageDto
     */
    type: object;
    /**
     * 
     * @type {object}
     * @memberof TournamentStageDto
     */
    settings: object;
    /**
     * 
     * @type {number}
     * @memberof TournamentStageDto
     */
    number: number;
}

export function TournamentStageDtoFromJSON(json: any): TournamentStageDto {
    return TournamentStageDtoFromJSONTyped(json, false);
}

export function TournamentStageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentStageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tournament_id': json['tournament_id'],
        'name': json['name'],
        'type': json['type'],
        'settings': json['settings'],
        'number': json['number'],
    };
}

export function TournamentStageDtoToJSON(value?: TournamentStageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tournament_id': value.tournament_id,
        'name': value.name,
        'type': value.type,
        'settings': value.settings,
        'number': value.number,
    };
}


