/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TournamentSmallTournamentDto,
    TournamentSmallTournamentDtoFromJSON,
    TournamentSmallTournamentDtoFromJSONTyped,
    TournamentSmallTournamentDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface TournamentRegistrationInvitationDto
 */
export class TournamentRegistrationInvitationDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentRegistrationInvitationDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentRegistrationInvitationDto
     */
    inviterSteamId: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentRegistrationInvitationDto
     */
    steamId: string;
    /**
     * 
     * @type {TournamentSmallTournamentDto}
     * @memberof TournamentRegistrationInvitationDto
     */
    tournament: TournamentSmallTournamentDto;
}

export function TournamentRegistrationInvitationDtoFromJSON(json: any): TournamentRegistrationInvitationDto {
    return TournamentRegistrationInvitationDtoFromJSONTyped(json, false);
}

export function TournamentRegistrationInvitationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentRegistrationInvitationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'inviterSteamId': json['inviterSteamId'],
        'steamId': json['steamId'],
        'tournament': TournamentSmallTournamentDtoFromJSON(json['tournament']),
    };
}

export function TournamentRegistrationInvitationDtoToJSON(value?: TournamentRegistrationInvitationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'inviterSteamId': value.inviterSteamId,
        'steamId': value.steamId,
        'tournament': TournamentSmallTournamentDtoToJSON(value.tournament),
    };
}


