/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentRegisterAsPartyDto
 */
export class TournamentRegisterAsPartyDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof TournamentRegisterAsPartyDto
     */
    steamIds: Array<string>;
}

export function TournamentRegisterAsPartyDtoFromJSON(json: any): TournamentRegisterAsPartyDto {
    return TournamentRegisterAsPartyDtoFromJSONTyped(json, false);
}

export function TournamentRegisterAsPartyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentRegisterAsPartyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'steamIds': json['steamIds'],
    };
}

export function TournamentRegisterAsPartyDtoToJSON(value?: TournamentRegisterAsPartyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'steamIds': value.steamIds,
    };
}


