// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentCreateTeamInviteDto
 */
export interface TournamentCreateTeamInviteDto {
  /**
   *
   * @type {string}
   * @memberof TournamentCreateTeamInviteDto
   */
  inviter: string;
  /**
   *
   * @type {string}
   * @memberof TournamentCreateTeamInviteDto
   */
  invited: string;
}
