// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TournamentTournamentParticipantDto } from './tournament-tournament-participant-dto';

/**
 * 
 * @export
 * @interface TournamentFullTournamentDto
 */
export interface TournamentFullTournamentDto {
    /**
     * 
     * @type {number}
     * @memberof TournamentFullTournamentDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TournamentFullTournamentDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentFullTournamentDto
     */
    entryType: TournamentFullTournamentDtoEntryTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TournamentFullTournamentDto
     */
    status: TournamentFullTournamentDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TournamentFullTournamentDto
     */
    startDate: number;
    /**
     * 
     * @type {string}
     * @memberof TournamentFullTournamentDto
     */
    imageUrl: string;
    /**
     * 
     * @type {Array<TournamentTournamentParticipantDto>}
     * @memberof TournamentFullTournamentDto
     */
    participants: Array<TournamentTournamentParticipantDto>;
}

/**
    * @export
    * @enum {string}
    */
export enum TournamentFullTournamentDtoEntryTypeEnum {
    PLAYER = 'PLAYER',
    TEAM = 'TEAM'
}
/**
    * @export
    * @enum {string}
    */
export enum TournamentFullTournamentDtoStatusEnum {
    NEW = 'NEW',
    ONGOING = 'ONGOING',
    FINISHED = 'FINISHED',
    CANCELLED = 'CANCELLED'
}



