/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TournamentCompactTeamDto, TournamentCompactTeamDtoFromJSON, TournamentCompactTeamDtoToJSON } from './';

/**
 *
 * @export
 * @interface TournamentTeamInvitationDto
 */
export class TournamentTeamInvitationDto {
    /**
     *
     * @type {TournamentCompactTeamDto}
     * @memberof TournamentTeamInvitationDto
     */
    team: TournamentCompactTeamDto;
    /**
     *
     * @type {number}
     * @memberof TournamentTeamInvitationDto
     */
    inviteId: number;
}

export function TournamentTeamInvitationDtoFromJSON(json: any): TournamentTeamInvitationDto {
    return TournamentTeamInvitationDtoFromJSONTyped(json, false);
}

export function TournamentTeamInvitationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentTeamInvitationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'team': TournamentCompactTeamDtoFromJSON(json['team']),
        'inviteId': json['inviteId'],
    };
}

export function TournamentTeamInvitationDtoToJSON(value?: TournamentTeamInvitationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'team': TournamentCompactTeamDtoToJSON(value.team),
        'inviteId': value.inviteId,
    };
}


