/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentSubmitInvitationDto
 */
export class TournamentSubmitInvitationDto {
    /**
     *
     * @type {boolean}
     * @memberof TournamentSubmitInvitationDto
     */
    accept: boolean;
}

export function TournamentSubmitInvitationDtoFromJSON(json: any): TournamentSubmitInvitationDto {
    return TournamentSubmitInvitationDtoFromJSONTyped(json, false);
}

export function TournamentSubmitInvitationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentSubmitInvitationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'accept': json['accept'],
    };
}

export function TournamentSubmitInvitationDtoToJSON(value?: TournamentSubmitInvitationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'accept': value.accept,
    };
}


