/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentRoundDto
 */
export class TournamentRoundDto {
    /**
     *
     * @type {number}
     * @memberof TournamentRoundDto
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof TournamentRoundDto
     */
    stage_id: number;
    /**
     *
     * @type {number}
     * @memberof TournamentRoundDto
     */
    group_id: number;
    /**
     *
     * @type {number}
     * @memberof TournamentRoundDto
     */
    number: number;
}

export function TournamentRoundDtoFromJSON(json: any): TournamentRoundDto {
    return TournamentRoundDtoFromJSONTyped(json, false);
}

export function TournamentRoundDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentRoundDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'stage_id': json['stage_id'],
        'group_id': json['group_id'],
        'number': json['number'],
    };
}

export function TournamentRoundDtoToJSON(value?: TournamentRoundDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'stage_id': value.stage_id,
        'group_id': value.group_id,
        'number': value.number,
    };
}


