/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  TournamentBracketMatchDto,
  TournamentBracketMatchDtoFromJSON,
  TournamentBracketMatchDtoToJSON,
  TournamentBracketParticipantDto,
  TournamentBracketParticipantDtoFromJSON,
  TournamentBracketParticipantDtoToJSON,
  TournamentGroupDto,
  TournamentGroupDtoFromJSON,
  TournamentGroupDtoToJSON,
  TournamentRoundDto,
  TournamentRoundDtoFromJSON,
  TournamentRoundDtoToJSON,
  TournamentStageDto,
  TournamentStageDtoFromJSON,
  TournamentStageDtoToJSON,
} from './';

/**
 *
 * @export
 * @interface TournamentTournamentBracketInfoDto
 */
export class TournamentTournamentBracketInfoDto {
    /**
     *
     * @type {Array<TournamentBracketParticipantDto>}
     * @memberof TournamentTournamentBracketInfoDto
     */
    participant: Array<TournamentBracketParticipantDto>;
    /**
     *
     * @type {Array<TournamentStageDto>}
     * @memberof TournamentTournamentBracketInfoDto
     */
    stage: Array<TournamentStageDto>;
    /**
     *
     * @type {Array<TournamentGroupDto>}
     * @memberof TournamentTournamentBracketInfoDto
     */
    group: Array<TournamentGroupDto>;
    /**
     *
     * @type {Array<TournamentRoundDto>}
     * @memberof TournamentTournamentBracketInfoDto
     */
    round: Array<TournamentRoundDto>;
    /**
     *
     * @type {Array<TournamentBracketMatchDto>}
     * @memberof TournamentTournamentBracketInfoDto
     */
    match: Array<TournamentBracketMatchDto>;
}

export function TournamentTournamentBracketInfoDtoFromJSON(json: any): TournamentTournamentBracketInfoDto {
    return TournamentTournamentBracketInfoDtoFromJSONTyped(json, false);
}

export function TournamentTournamentBracketInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentTournamentBracketInfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'participant': ((json['participant'] as Array<any>).map(TournamentBracketParticipantDtoFromJSON)),
        'stage': ((json['stage'] as Array<any>).map(TournamentStageDtoFromJSON)),
        'group': ((json['group'] as Array<any>).map(TournamentGroupDtoFromJSON)),
        'round': ((json['round'] as Array<any>).map(TournamentRoundDtoFromJSON)),
        'match': ((json['match'] as Array<any>).map(TournamentBracketMatchDtoFromJSON)),
    };
}

export function TournamentTournamentBracketInfoDtoToJSON(value?: TournamentTournamentBracketInfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'participant': ((value.participant as Array<any>).map(TournamentBracketParticipantDtoToJSON)),
        'stage': ((value.stage as Array<any>).map(TournamentStageDtoToJSON)),
        'group': ((value.group as Array<any>).map(TournamentGroupDtoToJSON)),
        'round': ((value.round as Array<any>).map(TournamentRoundDtoToJSON)),
        'match': ((value.match as Array<any>).map(TournamentBracketMatchDtoToJSON)),
    };
}


