/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
  TournamentBracketMatchGameDto,
  TournamentBracketMatchGameDtoFromJSON,
  TournamentBracketMatchGameDtoToJSON,
  TournamentMatchStatus,
  TournamentMatchStatusFromJSON,
  TournamentMatchStatusToJSON,
  TournamentParticipantResultDto,
  TournamentParticipantResultDtoFromJSON,
  TournamentParticipantResultDtoToJSON,
} from './';

/**
 *
 * @export
 * @interface TournamentBracketMatchDto
 */
export class TournamentBracketMatchDto {
    /**
     *
     * @type {TournamentMatchStatus}
     * @memberof TournamentBracketMatchDto
     */
    status: TournamentMatchStatus;
    /**
     *
     * @type {number}
     * @memberof TournamentBracketMatchDto
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof TournamentBracketMatchDto
     */
    stage_id: number;
    /**
     *
     * @type {number}
     * @memberof TournamentBracketMatchDto
     */
    group_id: number;
    /**
     *
     * @type {number}
     * @memberof TournamentBracketMatchDto
     */
    round_id: number;
    /**
     *
     * @type {number}
     * @memberof TournamentBracketMatchDto
     */
    child_count: number;
    /**
     *
     * @type {number}
     * @memberof TournamentBracketMatchDto
     */
    number: number;
    /**
     *
     * @type {TournamentParticipantResultDto}
     * @memberof TournamentBracketMatchDto
     */
    opponent1?: TournamentParticipantResultDto;
    /**
     *
     * @type {TournamentParticipantResultDto}
     * @memberof TournamentBracketMatchDto
     */
    opponent2?: TournamentParticipantResultDto;
    /**
     *
     * @type {Date}
     * @memberof TournamentBracketMatchDto
     */
    startDate: Date;
    /**
     *
     * @type {Array<TournamentBracketMatchGameDto>}
     * @memberof TournamentBracketMatchDto
     */
    games: Array<TournamentBracketMatchGameDto>;
}

export function TournamentBracketMatchDtoFromJSON(json: any): TournamentBracketMatchDto {
    return TournamentBracketMatchDtoFromJSONTyped(json, false);
}

export function TournamentBracketMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentBracketMatchDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'status': TournamentMatchStatusFromJSON(json['status']),
        'id': json['id'],
        'stage_id': json['stage_id'],
        'group_id': json['group_id'],
        'round_id': json['round_id'],
        'child_count': json['child_count'],
        'number': json['number'],
        'opponent1': !exists(json, 'opponent1') ? undefined : TournamentParticipantResultDtoFromJSON(json['opponent1']),
        'opponent2': !exists(json, 'opponent2') ? undefined : TournamentParticipantResultDtoFromJSON(json['opponent2']),
        'startDate': (new Date(json['startDate'])),
        'games': ((json['games'] as Array<any>).map(TournamentBracketMatchGameDtoFromJSON)),
    };
}

export function TournamentBracketMatchDtoToJSON(value?: TournamentBracketMatchDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'status': TournamentMatchStatusToJSON(value.status),
        'id': value.id,
        'stage_id': value.stage_id,
        'group_id': value.group_id,
        'round_id': value.round_id,
        'child_count': value.child_count,
        'number': value.number,
        'opponent1': TournamentParticipantResultDtoToJSON(value.opponent1),
        'opponent2': TournamentParticipantResultDtoToJSON(value.opponent2),
        'startDate': (value.startDate.toISOString()),
        'games': ((value.games as Array<any>).map(TournamentBracketMatchGameDtoToJSON)),
    };
}


