/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentKickFromTeamDto
 */
export class TournamentKickFromTeamDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentKickFromTeamDto
     */
    requesterSteamId: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentKickFromTeamDto
     */
    kickedSteamId: string;
}

export function TournamentKickFromTeamDtoFromJSON(json: any): TournamentKickFromTeamDto {
    return TournamentKickFromTeamDtoFromJSONTyped(json, false);
}

export function TournamentKickFromTeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentKickFromTeamDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requesterSteamId': json['requesterSteamId'],
        'kickedSteamId': json['kickedSteamId'],
    };
}

export function TournamentKickFromTeamDtoToJSON(value?: TournamentKickFromTeamDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requesterSteamId': value.requesterSteamId,
        'kickedSteamId': value.kickedSteamId,
    };
}


