/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentInviteToRegistrationDto
 */
export class TournamentInviteToRegistrationDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentInviteToRegistrationDto
     */
    inviterSteamId: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentInviteToRegistrationDto
     */
    steamId: string;
}

export function TournamentInviteToRegistrationDtoFromJSON(json: any): TournamentInviteToRegistrationDto {
    return TournamentInviteToRegistrationDtoFromJSONTyped(json, false);
}

export function TournamentInviteToRegistrationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentInviteToRegistrationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inviterSteamId': json['inviterSteamId'],
        'steamId': json['steamId'],
    };
}

export function TournamentInviteToRegistrationDtoToJSON(value?: TournamentInviteToRegistrationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inviterSteamId': value.inviterSteamId,
        'steamId': value.steamId,
    };
}


