/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TournamentRegistrationDto, TournamentRegistrationDtoFromJSON, TournamentRegistrationDtoToJSON } from './';

/**
 *
 * @export
 * @interface TournamentTournamentDto
 */
export class TournamentTournamentDto {
    /**
     *
     * @type {number}
     * @memberof TournamentTournamentDto
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof TournamentTournamentDto
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof TournamentTournamentDto
     */
    status: TournamentTournamentDtoStatusEnum;
    /**
     *
     * @type {Date}
     * @memberof TournamentTournamentDto
     */
    startDate: Date;
    /**
     *
     * @type {string}
     * @memberof TournamentTournamentDto
     */
    imageUrl: string;
    /**
     *
     * @type {string}
     * @memberof TournamentTournamentDto
     */
    description: string;
    /**
     *
     * @type {Array<TournamentRegistrationDto>}
     * @memberof TournamentTournamentDto
     */
    registrations: Array<TournamentRegistrationDto>;
}

export function TournamentTournamentDtoFromJSON(json: any): TournamentTournamentDto {
    return TournamentTournamentDtoFromJSONTyped(json, false);
}

export function TournamentTournamentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentTournamentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
        'status': json['status'],
        'startDate': (new Date(json['startDate'])),
        'imageUrl': json['imageUrl'],
        'description': json['description'],
        'registrations': ((json['registrations'] as Array<any>).map(TournamentRegistrationDtoFromJSON)),
    };
}

export function TournamentTournamentDtoToJSON(value?: TournamentTournamentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'name': value.name,
        'status': value.status,
        'startDate': (value.startDate.toISOString()),
        'imageUrl': value.imageUrl,
        'description': value.description,
        'registrations': ((value.registrations as Array<any>).map(TournamentRegistrationDtoToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum TournamentTournamentDtoStatusEnum {
    DRAFT = 'DRAFT',
    REGISTRATION = 'REGISTRATION',
    READYCHECK = 'READY_CHECK',
    INPROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED'
}


