/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TournamentBracketParticipantDto,
    TournamentBracketParticipantDtoFromJSON,
    TournamentBracketParticipantDtoFromJSONTyped,
    TournamentBracketParticipantDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface TournamentParticipantResultDto
 */
export class TournamentParticipantResultDto {
    /**
     * 
     * @type {number}
     * @memberof TournamentParticipantResultDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentParticipantResultDto
     */
    position?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TournamentParticipantResultDto
     */
    forfeit?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TournamentParticipantResultDto
     */
    score?: number;
    /**
     * 
     * @type {object}
     * @memberof TournamentParticipantResultDto
     */
    result?: object;
    /**
     * 
     * @type {boolean}
     * @memberof TournamentParticipantResultDto
     */
    tbd?: boolean;
    /**
     * 
     * @type {TournamentBracketParticipantDto}
     * @memberof TournamentParticipantResultDto
     */
    participant?: TournamentBracketParticipantDto;
}

export function TournamentParticipantResultDtoFromJSON(json: any): TournamentParticipantResultDto {
    return TournamentParticipantResultDtoFromJSONTyped(json, false);
}

export function TournamentParticipantResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentParticipantResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'position': !exists(json, 'position') ? undefined : json['position'],
        'forfeit': !exists(json, 'forfeit') ? undefined : json['forfeit'],
        'score': !exists(json, 'score') ? undefined : json['score'],
        'result': !exists(json, 'result') ? undefined : json['result'],
        'tbd': !exists(json, 'tbd') ? undefined : json['tbd'],
        'participant': !exists(json, 'participant') ? undefined : TournamentBracketParticipantDtoFromJSON(json['participant']),
    };
}

export function TournamentParticipantResultDtoToJSON(value?: TournamentParticipantResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'position': value.position,
        'forfeit': value.forfeit,
        'score': value.score,
        'result': value.result,
        'tbd': value.tbd,
        'participant': TournamentBracketParticipantDtoToJSON(value.participant),
    };
}


