/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentTeamMemberDto
 */
export class TournamentTeamMemberDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentTeamMemberDto
     */
    steam_id: string;
}

export function TournamentTeamMemberDtoFromJSON(json: any): TournamentTeamMemberDto {
    return TournamentTeamMemberDtoFromJSONTyped(json, false);
}

export function TournamentTeamMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentTeamMemberDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'steam_id': json['steam_id'],
    };
}

export function TournamentTeamMemberDtoToJSON(value?: TournamentTeamMemberDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'steam_id': value.steam_id,
    };
}


