/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TournamentTeamDto,
    TournamentTeamDtoFromJSON,
    TournamentTeamDtoFromJSONTyped,
    TournamentTeamDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface TournamentSeedItemDto
 */
export class TournamentSeedItemDto {
    /**
     * 
     * @type {number}
     * @memberof TournamentSeedItemDto
     */
    id: number;
    /**
     * 
     * @type {object}
     * @memberof TournamentSeedItemDto
     */
    result?: object;
    /**
     * 
     * @type {TournamentTeamDto}
     * @memberof TournamentSeedItemDto
     */
    team?: TournamentTeamDto;
    /**
     * 
     * @type {boolean}
     * @memberof TournamentSeedItemDto
     */
    tbd?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TournamentSeedItemDto
     */
    score?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TournamentSeedItemDto
     */
    players: Array<string>;
}

export function TournamentSeedItemDtoFromJSON(json: any): TournamentSeedItemDto {
    return TournamentSeedItemDtoFromJSONTyped(json, false);
}

export function TournamentSeedItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentSeedItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'result': !exists(json, 'result') ? undefined : json['result'],
        'team': !exists(json, 'team') ? undefined : TournamentTeamDtoFromJSON(json['team']),
        'tbd': !exists(json, 'tbd') ? undefined : json['tbd'],
        'score': !exists(json, 'score') ? undefined : json['score'],
        'players': json['players'],
    };
}

export function TournamentSeedItemDtoToJSON(value?: TournamentSeedItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'result': value.result,
        'team': TournamentTeamDtoToJSON(value.team),
        'tbd': value.tbd,
        'score': value.score,
        'players': value.players,
    };
}


