// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TournamentCreateTeamDto
 */
export interface TournamentCreateTeamDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentCreateTeamDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCreateTeamDto
     */
    tag: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCreateTeamDto
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCreateTeamDto
     */
    creator: string;
}


