/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TournamentSeedDto, TournamentSeedDtoFromJSON, TournamentSeedDtoToJSON, } from "./";

/**
 *
 * @export
 * @interface TournamentBracketRoundDto
 */
export class TournamentBracketRoundDto {
    /**
     *
     * @type {string}
     * @memberof TournamentBracketRoundDto
     */
    title: string;
    /**
     *
     * @type {number}
     * @memberof TournamentBracketRoundDto
     */
    round: number;
    /**
     *
     * @type {Array<TournamentSeedDto>}
     * @memberof TournamentBracketRoundDto
     */
    seeds: Array<TournamentSeedDto>;
}

export function TournamentBracketRoundDtoFromJSON(json: any): TournamentBracketRoundDto {
    return TournamentBracketRoundDtoFromJSONTyped(json, false);
}

export function TournamentBracketRoundDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentBracketRoundDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'title': json['title'],
        'round': json['round'],
        'seeds': ((json['seeds'] as Array<any>).map(TournamentSeedDtoFromJSON)),
    };
}

export function TournamentBracketRoundDtoToJSON(value?: TournamentBracketRoundDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'title': value.title,
        'round': value.round,
        'seeds': ((value.seeds as Array<any>).map(TournamentSeedDtoToJSON)),
    };
}


