/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TournamentBracketRoundDto, TournamentBracketRoundDtoFromJSON, TournamentBracketRoundDtoToJSON } from './';

/**
 *
 * @export
 * @interface TournamentBracketDto
 */
export class TournamentBracketDto {
    /**
     *
     * @type {string}
     * @memberof TournamentBracketDto
     */
    type: TournamentBracketDtoTypeEnum;
    /**
     *
     * @type {Array<TournamentBracketRoundDto>}
     * @memberof TournamentBracketDto
     */
    winning: Array<TournamentBracketRoundDto>;
    /**
     *
     * @type {Array<TournamentBracketRoundDto>}
     * @memberof TournamentBracketDto
     */
    losing: Array<TournamentBracketRoundDto>;
}

export function TournamentBracketDtoFromJSON(json: any): TournamentBracketDto {
    return TournamentBracketDtoFromJSONTyped(json, false);
}

export function TournamentBracketDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentBracketDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'type': json['type'],
        'winning': ((json['winning'] as Array<any>).map(TournamentBracketRoundDtoFromJSON)),
        'losing': ((json['losing'] as Array<any>).map(TournamentBracketRoundDtoFromJSON)),
    };
}

export function TournamentBracketDtoToJSON(value?: TournamentBracketDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'type': value.type,
        'winning': ((value.winning as Array<any>).map(TournamentBracketRoundDtoToJSON)),
        'losing': ((value.losing as Array<any>).map(TournamentBracketRoundDtoToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum TournamentBracketDtoTypeEnum {
    SINGLEELIMINATION = 'SINGLE_ELIMINATION',
    DOUBLEELIMINATION = 'DOUBLE_ELIMINATION'
}


