/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentStartGameDto
 */
export class TournamentStartGameDto {
    /**
     *
     * @type {string}
     * @memberof TournamentStartGameDto
     */
    gameId: string;
}

export function TournamentStartGameDtoFromJSON(json: any): TournamentStartGameDto {
    return TournamentStartGameDtoFromJSONTyped(json, false);
}

export function TournamentStartGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentStartGameDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'gameId': json['gameId'],
    };
}

export function TournamentStartGameDtoToJSON(value?: TournamentStartGameDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'gameId': value.gameId,
    };
}


