/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentGroupDto
 */
export class TournamentGroupDto {
    /**
     * 
     * @type {number}
     * @memberof TournamentGroupDto
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentGroupDto
     */
    stage_id: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentGroupDto
     */
    number: number;
}

export function TournamentGroupDtoFromJSON(json: any): TournamentGroupDto {
    return TournamentGroupDtoFromJSONTyped(json, false);
}

export function TournamentGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentGroupDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'stage_id': json['stage_id'],
        'number': json['number'],
    };
}

export function TournamentGroupDtoToJSON(value?: TournamentGroupDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'stage_id': value.stage_id,
        'number': value.number,
    };
}


