/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
  TournamentMatchStatus,
  TournamentMatchStatusFromJSON,
  TournamentMatchStatusToJSON,
  TournamentSeedItemDto,
  TournamentSeedItemDtoFromJSON,
  TournamentSeedItemDtoToJSON,
} from './';

/**
 *
 * @export
 * @interface TournamentMatchGameDto
 */
export class TournamentMatchGameDto {
    /**
     *
     * @type {TournamentMatchStatus}
     * @memberof TournamentMatchGameDto
     */
    status: TournamentMatchStatus;
    /**
     *
     * @type {string}
     * @memberof TournamentMatchGameDto
     */
    gameId: string;
    /**
     *
     * @type {number}
     * @memberof TournamentMatchGameDto
     */
    bracketMatchId: number;
    /**
     *
     * @type {number}
     * @memberof TournamentMatchGameDto
     */
    externalMatchId?: number;
    /**
     *
     * @type {string}
     * @memberof TournamentMatchGameDto
     */
    scheduledDate?: string;
    /**
     *
     * @type {number}
     * @memberof TournamentMatchGameDto
     */
    teamOffset: number;
    /**
     *
     * @type {number}
     * @memberof TournamentMatchGameDto
     */
    number: number;
    /**
     *
     * @type {TournamentSeedItemDto}
     * @memberof TournamentMatchGameDto
     */
    opponent1?: TournamentSeedItemDto;
    /**
     *
     * @type {TournamentSeedItemDto}
     * @memberof TournamentMatchGameDto
     */
    opponent2?: TournamentSeedItemDto;
}

export function TournamentMatchGameDtoFromJSON(json: any): TournamentMatchGameDto {
    return TournamentMatchGameDtoFromJSONTyped(json, false);
}

export function TournamentMatchGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentMatchGameDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'status': TournamentMatchStatusFromJSON(json['status']),
        'gameId': json['gameId'],
        'bracketMatchId': json['bracketMatchId'],
        'externalMatchId': !exists(json, 'externalMatchId') ? undefined : json['externalMatchId'],
        'scheduledDate': !exists(json, 'scheduledDate') ? undefined : json['scheduledDate'],
        'teamOffset': json['teamOffset'],
        'number': json['number'],
        'opponent1': !exists(json, 'opponent1') ? undefined : TournamentSeedItemDtoFromJSON(json['opponent1']),
        'opponent2': !exists(json, 'opponent2') ? undefined : TournamentSeedItemDtoFromJSON(json['opponent2']),
    };
}

export function TournamentMatchGameDtoToJSON(value?: TournamentMatchGameDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'status': TournamentMatchStatusToJSON(value.status),
        'gameId': value.gameId,
        'bracketMatchId': value.bracketMatchId,
        'externalMatchId': value.externalMatchId,
        'scheduledDate': value.scheduledDate,
        'teamOffset': value.teamOffset,
        'number': value.number,
        'opponent1': TournamentSeedItemDtoToJSON(value.opponent1),
        'opponent2': TournamentSeedItemDtoToJSON(value.opponent2),
    };
}


