/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentScheduleStrategy
 */
export class TournamentScheduleStrategy {
    /**
     *
     * @type {number}
     * @memberof TournamentScheduleStrategy
     */
    gameDurationSeconds: number;
    /**
     *
     * @type {number}
     * @memberof TournamentScheduleStrategy
     */
    gameBreakDurationSeconds: number;
}

export function TournamentScheduleStrategyFromJSON(json: any): TournamentScheduleStrategy {
    return TournamentScheduleStrategyFromJSONTyped(json, false);
}

export function TournamentScheduleStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentScheduleStrategy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'gameDurationSeconds': json['gameDurationSeconds'],
        'gameBreakDurationSeconds': json['gameBreakDurationSeconds'],
    };
}

export function TournamentScheduleStrategyToJSON(value?: TournamentScheduleStrategy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'gameDurationSeconds': value.gameDurationSeconds,
        'gameBreakDurationSeconds': value.gameBreakDurationSeconds,
    };
}


