// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TournamentSeedItemDto } from './tournament-seed-item-dto';

/**
 * 
 * @export
 * @interface TournamentSeedDto
 */
export interface TournamentSeedDto {
    /**
     * 
     * @type {Array<TournamentSeedItemDto>}
     * @memberof TournamentSeedDto
     */
    teams: Array<TournamentSeedItemDto>;
    /**
     * 
     * @type {string}
     * @memberof TournamentSeedDto
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof TournamentSeedDto
     */
    matchId?: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentSeedDto
     */
    id: number;
}


