// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TournamentSubmitInvitationDto
 */
export interface TournamentSubmitInvitationDto {
    /**
     * 
     * @type {boolean}
     * @memberof TournamentSubmitInvitationDto
     */
    accept: boolean;
}


