/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentCreateTournamentDto
 */
export class TournamentCreateTournamentDto {
    /**
     *
     * @type {string}
     * @memberof TournamentCreateTournamentDto
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof TournamentCreateTournamentDto
     */
    teamSize: number;
    /**
     *
     * @type {string}
     * @memberof TournamentCreateTournamentDto
     */
    description: string;
    /**
     *
     * @type {Date}
     * @memberof TournamentCreateTournamentDto
     */
    startDate: Date;
    /**
     *
     * @type {string}
     * @memberof TournamentCreateTournamentDto
     */
    imageUrl: string;
    /**
     *
     * @type {string}
     * @memberof TournamentCreateTournamentDto
     */
    strategy: TournamentCreateTournamentDtoStrategyEnum;
    /**
     *
     * @type {number}
     * @memberof TournamentCreateTournamentDto
     */
    roundBestOf: number;
    /**
     *
     * @type {number}
     * @memberof TournamentCreateTournamentDto
     */
    finalBestOf: number;
    /**
     *
     * @type {number}
     * @memberof TournamentCreateTournamentDto
     */
    grandFinalBestOf: number;
}

export function TournamentCreateTournamentDtoFromJSON(json: any): TournamentCreateTournamentDto {
    return TournamentCreateTournamentDtoFromJSONTyped(json, false);
}

export function TournamentCreateTournamentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentCreateTournamentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'name': json['name'],
        'teamSize': json['teamSize'],
        'description': json['description'],
        'startDate': (new Date(json['startDate'])),
        'imageUrl': json['imageUrl'],
        'strategy': json['strategy'],
        'roundBestOf': json['roundBestOf'],
        'finalBestOf': json['finalBestOf'],
        'grandFinalBestOf': json['grandFinalBestOf'],
    };
}

export function TournamentCreateTournamentDtoToJSON(value?: TournamentCreateTournamentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'name': value.name,
        'teamSize': value.teamSize,
        'description': value.description,
        'startDate': (value.startDate.toISOString()),
        'imageUrl': value.imageUrl,
        'strategy': value.strategy,
        'roundBestOf': value.roundBestOf,
        'finalBestOf': value.finalBestOf,
        'grandFinalBestOf': value.grandFinalBestOf,
    };
}

/**
* @export
* @enum {string}
*/
export enum TournamentCreateTournamentDtoStrategyEnum {
    SINGLEELIMINATION = 'SINGLE_ELIMINATION',
    DOUBLEELIMINATION = 'DOUBLE_ELIMINATION'
}


