// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TournamentTeamMemberDto } from './tournament-team-member-dto';

/**
 * 
 * @export
 * @interface TournamentTeamDto
 */
export interface TournamentTeamDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentTeamDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentTeamDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentTeamDto
     */
    tag: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentTeamDto
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentTeamDto
     */
    creator: string;
    /**
     * 
     * @type {Array<TournamentTeamMemberDto>}
     * @memberof TournamentTeamDto
     */
    members: Array<TournamentTeamMemberDto>;
}


