// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TournamentSeedItemDto } from './tournament-seed-item-dto';

/**
 * 
 * @export
 * @interface TournamentTournamentMatchDto
 */
export interface TournamentTournamentMatchDto {
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    stage_id: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    group_id: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    round_id: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    child_count: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof TournamentTournamentMatchDto
     */
    status: TournamentTournamentMatchDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    scheduledDate: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    externalMatchId: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentTournamentMatchDto
     */
    teamOffset: number;
    /**
     * 
     * @type {TournamentSeedItemDto}
     * @memberof TournamentTournamentMatchDto
     */
    opponent1?: TournamentSeedItemDto;
    /**
     * 
     * @type {TournamentSeedItemDto}
     * @memberof TournamentTournamentMatchDto
     */
    opponent2?: TournamentSeedItemDto;
}

/**
    * @export
    * @enum {string}
    */
export enum TournamentTournamentMatchDtoStatusEnum {
    Locked = 'Locked',
    Waiting = 'Waiting',
    Ready = 'Ready',
    Running = 'Running',
    Completed = 'Completed',
    Archived = 'Archived'
}



