// tslint:disable
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TournamentCompactTeamDto } from './tournament-compact-team-dto';

/**
 *
 * @export
 * @interface TournamentTeamInvitationDto
 */
export interface TournamentTeamInvitationDto {
  /**
   *
   * @type {TournamentCompactTeamDto}
   * @memberof TournamentTeamInvitationDto
   */
  team: TournamentCompactTeamDto;
  /**
   *
   * @type {number}
   * @memberof TournamentTeamInvitationDto
   */
  inviteId: number;
}
