/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentEditTeamDto
 */
export class TournamentEditTeamDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentEditTeamDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentEditTeamDto
     */
    tag?: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentEditTeamDto
     */
    imageUrl?: string;
}

export function TournamentEditTeamDtoFromJSON(json: any): TournamentEditTeamDto {
    return TournamentEditTeamDtoFromJSONTyped(json, false);
}

export function TournamentEditTeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentEditTeamDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
    };
}

export function TournamentEditTeamDtoToJSON(value?: TournamentEditTeamDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'tag': value.tag,
        'imageUrl': value.imageUrl,
    };
}


