/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentSmallTournamentDto
 */
export class TournamentSmallTournamentDto {
    /**
     *
     * @type {number}
     * @memberof TournamentSmallTournamentDto
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof TournamentSmallTournamentDto
     */
    name: string;
}

export function TournamentSmallTournamentDtoFromJSON(json: any): TournamentSmallTournamentDto {
    return TournamentSmallTournamentDtoFromJSONTyped(json, false);
}

export function TournamentSmallTournamentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentSmallTournamentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
    };
}

export function TournamentSmallTournamentDtoToJSON(value?: TournamentSmallTournamentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'name': value.name,
    };
}


