/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentCreateTeamInviteDto
 */
export class TournamentCreateTeamInviteDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentCreateTeamInviteDto
     */
    inviter: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentCreateTeamInviteDto
     */
    invited: string;
}

export function TournamentCreateTeamInviteDtoFromJSON(json: any): TournamentCreateTeamInviteDto {
    return TournamentCreateTeamInviteDtoFromJSONTyped(json, false);
}

export function TournamentCreateTeamInviteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentCreateTeamInviteDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inviter': json['inviter'],
        'invited': json['invited'],
    };
}

export function TournamentCreateTeamInviteDtoToJSON(value?: TournamentCreateTeamInviteDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inviter': value.inviter,
        'invited': value.invited,
    };
}


