/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TournamentSetGameWinnerDto
 */
export class TournamentSetGameWinnerDto {
    /**
     * 
     * @type {string}
     * @memberof TournamentSetGameWinnerDto
     */
    gameId: string;
    /**
     * 
     * @type {number}
     * @memberof TournamentSetGameWinnerDto
     */
    winnerId: number;
    /**
     * 
     * @type {number}
     * @memberof TournamentSetGameWinnerDto
     */
    d2cMatchId?: number;
}

export function TournamentSetGameWinnerDtoFromJSON(json: any): TournamentSetGameWinnerDto {
    return TournamentSetGameWinnerDtoFromJSONTyped(json, false);
}

export function TournamentSetGameWinnerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentSetGameWinnerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameId': json['gameId'],
        'winnerId': json['winnerId'],
        'd2cMatchId': !exists(json, 'd2cMatchId') ? undefined : json['d2cMatchId'],
    };
}

export function TournamentSetGameWinnerDtoToJSON(value?: TournamentSetGameWinnerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gameId': value.gameId,
        'winnerId': value.winnerId,
        'd2cMatchId': value.d2cMatchId,
    };
}


