/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentUnregisterPlayerDto
 */
export class TournamentUnregisterPlayerDto {
    /**
     *
     * @type {string}
     * @memberof TournamentUnregisterPlayerDto
     */
    steamId: string;
}

export function TournamentUnregisterPlayerDtoFromJSON(json: any): TournamentUnregisterPlayerDto {
    return TournamentUnregisterPlayerDtoFromJSONTyped(json, false);
}

export function TournamentUnregisterPlayerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentUnregisterPlayerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'steamId': json['steamId'],
    };
}

export function TournamentUnregisterPlayerDtoToJSON(value?: TournamentUnregisterPlayerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'steamId': value.steamId,
    };
}


