/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentConfirmRegistrationDto
 */
export class TournamentConfirmRegistrationDto {
    /**
     *
     * @type {string}
     * @memberof TournamentConfirmRegistrationDto
     */
    steamId: string;
    /**
     *
     * @type {boolean}
     * @memberof TournamentConfirmRegistrationDto
     */
    confirm: boolean;
}

export function TournamentConfirmRegistrationDtoFromJSON(json: any): TournamentConfirmRegistrationDto {
    return TournamentConfirmRegistrationDtoFromJSONTyped(json, false);
}

export function TournamentConfirmRegistrationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentConfirmRegistrationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'steamId': json['steamId'],
        'confirm': json['confirm'],
    };
}

export function TournamentConfirmRegistrationDtoToJSON(value?: TournamentConfirmRegistrationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'steamId': value.steamId,
        'confirm': value.confirm,
    };
}


