/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TournamentBestOfStrategy
 */
export class TournamentBestOfStrategy {
    /**
     *
     * @type {number}
     * @memberof TournamentBestOfStrategy
     */
    round: number;
    /**
     *
     * @type {number}
     * @memberof TournamentBestOfStrategy
     */
    final: number;
    /**
     *
     * @type {number}
     * @memberof TournamentBestOfStrategy
     */
    grandFinal: number;
}

export function TournamentBestOfStrategyFromJSON(json: any): TournamentBestOfStrategy {
    return TournamentBestOfStrategyFromJSONTyped(json, false);
}

export function TournamentBestOfStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentBestOfStrategy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'round': json['round'],
        'final': json['final'],
        'grandFinal': json['grandFinal'],
    };
}

export function TournamentBestOfStrategyToJSON(value?: TournamentBestOfStrategy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'round': value.round,
        'final': value.final,
        'grandFinal': value.grandFinal,
    };
}


