/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

import {
    TournamentBracketDto,
    TournamentBracketDtoFromJSON,
    TournamentBracketDtoToJSON,
    TournamentBracketMatchDto,
    TournamentBracketMatchDtoFromJSON,
    TournamentBracketMatchDtoToJSON,
    TournamentConfirmRegistrationDto,
    TournamentConfirmRegistrationDtoFromJSON,
    TournamentConfirmRegistrationDtoToJSON,
    TournamentCreateTournamentDto,
    TournamentCreateTournamentDtoFromJSON,
    TournamentCreateTournamentDtoToJSON,
    TournamentInviteToRegistrationDto,
    TournamentInviteToRegistrationDtoFromJSON,
    TournamentInviteToRegistrationDtoToJSON,
    TournamentRegisterAsPartyDto,
    TournamentRegisterAsPartyDtoFromJSON,
    TournamentRegisterAsPartyDtoToJSON,
    TournamentRegistrationInvitationDto,
    TournamentRegistrationInvitationDtoFromJSON,
    TournamentRegistrationInvitationDtoToJSON,
    TournamentReplyRegistrationInvitationDto,
    TournamentReplyRegistrationInvitationDtoFromJSON,
    TournamentReplyRegistrationInvitationDtoToJSON,
    TournamentResetGameDataDto,
    TournamentResetGameDataDtoFromJSON,
    TournamentResetGameDataDtoToJSON,
    TournamentScheduleTournamentGameDto,
    TournamentScheduleTournamentGameDtoFromJSON,
    TournamentScheduleTournamentGameDtoToJSON,
    TournamentSetGameWinnerDto,
    TournamentSetGameWinnerDtoFromJSON,
    TournamentSetGameWinnerDtoToJSON,
    TournamentStageStandingsResultDto,
    TournamentStageStandingsResultDtoFromJSON,
    TournamentStageStandingsResultDtoToJSON,
    TournamentStartGameDto,
    TournamentStartGameDtoFromJSON,
    TournamentStartGameDtoToJSON,
    TournamentTournamentBracketInfoDto,
    TournamentTournamentBracketInfoDtoFromJSON,
    TournamentTournamentBracketInfoDtoToJSON,
    TournamentTournamentDto,
    TournamentTournamentDtoFromJSON,
    TournamentTournamentDtoToJSON,
    TournamentUnregisterPlayerDto,
    TournamentUnregisterPlayerDtoFromJSON,
    TournamentUnregisterPlayerDtoToJSON,
    TournamentUpdateTournamentDto,
    TournamentUpdateTournamentDtoFromJSON,
    TournamentUpdateTournamentDtoToJSON,
} from '../models';

export interface TournamentControllerAutoScheduleBracketRequest {
    id: number;
}

export interface TournamentControllerConfirmRegistrationRequest {
    id: number;
    tournamentConfirmRegistrationDto: TournamentConfirmRegistrationDto;
}

export interface TournamentControllerCreateTournamentRequest {
    tournamentCreateTournamentDto: TournamentCreateTournamentDto;
}

export interface TournamentControllerEndReadyCheckRequest {
    id: number;
}

export interface TournamentControllerEndRegistrationRequest {
    id: number;
}

export interface TournamentControllerFinishTournamentRequest {
    id: number;
}

export interface TournamentControllerGetBracketRequest {
    id: number;
}

export interface TournamentControllerGetBracketRenderRequest {
    id: number;
}

export interface TournamentControllerGetInvitationRequest {
    id: string;
}

export interface TournamentControllerGetMatchRequest {
    id: number;
    matchId: number;
}

export interface TournamentControllerGetTournamentRequest {
    id: number;
}

export interface TournamentControllerGetTournamentMatchesRequest {
    id: number;
}

export interface TournamentControllerGetTournamentStandingsRequest {
    id: number;
}

export interface TournamentControllerInviteToRegistrationRequest {
    id: number;
    tournamentInviteToRegistrationDto: TournamentInviteToRegistrationDto;
}

export interface TournamentControllerPublishTournamentRequest {
    id: number;
}

export interface TournamentControllerRegisterRequest {
    id: number;
    tournamentRegisterAsPartyDto: TournamentRegisterAsPartyDto;
}

export interface TournamentControllerReplyRegistrationInvitationRequest {
    id: number;
    tournamentReplyRegistrationInvitationDto: TournamentReplyRegistrationInvitationDto;
}

export interface TournamentControllerResetGameDataRequest {
    id: number;
    tournamentResetGameDataDto: TournamentResetGameDataDto;
}

export interface TournamentControllerScheduleMatchRequest {
    id: number;
    tournamentScheduleTournamentGameDto: TournamentScheduleTournamentGameDto;
}

export interface TournamentControllerSetGameWinnerRequest {
    id: number;
    tournamentSetGameWinnerDto: TournamentSetGameWinnerDto;
}

export interface TournamentControllerStartGameRequest {
    id: number;
    tournamentStartGameDto: TournamentStartGameDto;
}

export interface TournamentControllerStartTournamentRequest {
    id: number;
}

export interface TournamentControllerUnregisterRequest {
    id: number;
    tournamentUnregisterPlayerDto: TournamentUnregisterPlayerDto;
}

export interface TournamentControllerUpdateTournamentRequest {
    id: number;
    tournamentUpdateTournamentDto: TournamentUpdateTournamentDto;
}

/**
 * 
 */
export class TournamentApi extends runtime.BaseAPI {

    /**
     */
    private async tournamentControllerAutoScheduleBracketRaw(requestParameters: TournamentControllerAutoScheduleBracketRequest): Promise<runtime.ApiResponse<TournamentBracketDto>> {
        this.tournamentControllerAutoScheduleBracketValidation(requestParameters);
        const context = this.tournamentControllerAutoScheduleBracketContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentBracketDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerAutoScheduleBracketValidation(requestParameters: TournamentControllerAutoScheduleBracketRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerAutoScheduleBracket.');
        }
    }

    /**
     */
    tournamentControllerAutoScheduleBracketContext(requestParameters: TournamentControllerAutoScheduleBracketRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/auto_schedule_bracket`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerAutoScheduleBracket = async (id: number): Promise<TournamentBracketDto> => {
        const response = await this.tournamentControllerAutoScheduleBracketRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerConfirmRegistrationRaw(requestParameters: TournamentControllerConfirmRegistrationRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerConfirmRegistrationValidation(requestParameters);
        const context = this.tournamentControllerConfirmRegistrationContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerConfirmRegistrationValidation(requestParameters: TournamentControllerConfirmRegistrationRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerConfirmRegistration.');
        }
        if (requestParameters.tournamentConfirmRegistrationDto === null || requestParameters.tournamentConfirmRegistrationDto === undefined) {
            throw new runtime.RequiredError('tournamentConfirmRegistrationDto','Required parameter requestParameters.tournamentConfirmRegistrationDto was null or undefined when calling tournamentControllerConfirmRegistration.');
        }
    }

    /**
     */
    tournamentControllerConfirmRegistrationContext(requestParameters: TournamentControllerConfirmRegistrationRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/confirm_registration`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentConfirmRegistrationDtoToJSON(requestParameters.tournamentConfirmRegistrationDto),
        };
    }

    /**
     */
    tournamentControllerConfirmRegistration = async (id: number, tournamentConfirmRegistrationDto: TournamentConfirmRegistrationDto): Promise<void> => {
        await this.tournamentControllerConfirmRegistrationRaw({ id: id, tournamentConfirmRegistrationDto: tournamentConfirmRegistrationDto });
    }

    /**
     */
    private async tournamentControllerCreateTournamentRaw(requestParameters: TournamentControllerCreateTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerCreateTournamentValidation(requestParameters);
        const context = this.tournamentControllerCreateTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerCreateTournamentValidation(requestParameters: TournamentControllerCreateTournamentRequest) {
        if (requestParameters.tournamentCreateTournamentDto === null || requestParameters.tournamentCreateTournamentDto === undefined) {
            throw new runtime.RequiredError('tournamentCreateTournamentDto','Required parameter requestParameters.tournamentCreateTournamentDto was null or undefined when calling tournamentControllerCreateTournament.');
        }
    }

    /**
     */
    tournamentControllerCreateTournamentContext(requestParameters: TournamentControllerCreateTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentCreateTournamentDtoToJSON(requestParameters.tournamentCreateTournamentDto),
        };
    }

    /**
     */
    tournamentControllerCreateTournament = async (tournamentCreateTournamentDto: TournamentCreateTournamentDto): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerCreateTournamentRaw({ tournamentCreateTournamentDto: tournamentCreateTournamentDto });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerEndReadyCheckRaw(requestParameters: TournamentControllerEndReadyCheckRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerEndReadyCheckValidation(requestParameters);
        const context = this.tournamentControllerEndReadyCheckContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerEndReadyCheckValidation(requestParameters: TournamentControllerEndReadyCheckRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerEndReadyCheck.');
        }
    }

    /**
     */
    tournamentControllerEndReadyCheckContext(requestParameters: TournamentControllerEndReadyCheckRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/end_ready_check`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerEndReadyCheck = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerEndReadyCheckRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerEndRegistrationRaw(requestParameters: TournamentControllerEndRegistrationRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerEndRegistrationValidation(requestParameters);
        const context = this.tournamentControllerEndRegistrationContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerEndRegistrationValidation(requestParameters: TournamentControllerEndRegistrationRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerEndRegistration.');
        }
    }

    /**
     */
    tournamentControllerEndRegistrationContext(requestParameters: TournamentControllerEndRegistrationRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/end_registration`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerEndRegistration = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerEndRegistrationRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerFinishTournamentRaw(requestParameters: TournamentControllerFinishTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerFinishTournamentValidation(requestParameters);
        const context = this.tournamentControllerFinishTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerFinishTournamentValidation(requestParameters: TournamentControllerFinishTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerFinishTournament.');
        }
    }

    /**
     */
    tournamentControllerFinishTournamentContext(requestParameters: TournamentControllerFinishTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/finish_tournament`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerFinishTournament = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerFinishTournamentRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetBracketRaw(requestParameters: TournamentControllerGetBracketRequest): Promise<runtime.ApiResponse<TournamentBracketDto>> {
        this.tournamentControllerGetBracketValidation(requestParameters);
        const context = this.tournamentControllerGetBracketContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentBracketDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerGetBracketValidation(requestParameters: TournamentControllerGetBracketRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetBracket.');
        }
    }

    /**
     */
    tournamentControllerGetBracketContext(requestParameters: TournamentControllerGetBracketRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/bracket`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetBracket = async (id: number): Promise<TournamentBracketDto> => {
        const response = await this.tournamentControllerGetBracketRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetBracketRenderRaw(requestParameters: TournamentControllerGetBracketRenderRequest): Promise<runtime.ApiResponse<TournamentTournamentBracketInfoDto>> {
        this.tournamentControllerGetBracketRenderValidation(requestParameters);
        const context = this.tournamentControllerGetBracketRenderContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentBracketInfoDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerGetBracketRenderValidation(requestParameters: TournamentControllerGetBracketRenderRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetBracketRender.');
        }
    }

    /**
     */
    tournamentControllerGetBracketRenderContext(requestParameters: TournamentControllerGetBracketRenderRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/bracket_render`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetBracketRender = async (id: number): Promise<TournamentTournamentBracketInfoDto> => {
        const response = await this.tournamentControllerGetBracketRenderRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetInvitationRaw(requestParameters: TournamentControllerGetInvitationRequest): Promise<runtime.ApiResponse<TournamentRegistrationInvitationDto>> {
        this.tournamentControllerGetInvitationValidation(requestParameters);
        const context = this.tournamentControllerGetInvitationContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentRegistrationInvitationDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerGetInvitationValidation(requestParameters: TournamentControllerGetInvitationRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetInvitation.');
        }
    }

    /**
     */
    tournamentControllerGetInvitationContext(requestParameters: TournamentControllerGetInvitationRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/registration_invitation/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetInvitation = async (id: string): Promise<TournamentRegistrationInvitationDto> => {
        const response = await this.tournamentControllerGetInvitationRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetMatchRaw(requestParameters: TournamentControllerGetMatchRequest): Promise<runtime.ApiResponse<TournamentBracketMatchDto>> {
        this.tournamentControllerGetMatchValidation(requestParameters);
        const context = this.tournamentControllerGetMatchContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentBracketMatchDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerGetMatchValidation(requestParameters: TournamentControllerGetMatchRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetMatch.');
        }
        if (requestParameters.matchId === null || requestParameters.matchId === undefined) {
            throw new runtime.RequiredError('matchId','Required parameter requestParameters.matchId was null or undefined when calling tournamentControllerGetMatch.');
        }
    }

    /**
     */
    tournamentControllerGetMatchContext(requestParameters: TournamentControllerGetMatchRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/match_info/{match_id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"match_id"}}`, encodeURIComponent(String(requestParameters.matchId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetMatch = async (id: number, matchId: number): Promise<TournamentBracketMatchDto> => {
        const response = await this.tournamentControllerGetMatchRaw({ id: id, matchId: matchId });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetTournamentRaw(requestParameters: TournamentControllerGetTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerGetTournamentValidation(requestParameters);
        const context = this.tournamentControllerGetTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerGetTournamentValidation(requestParameters: TournamentControllerGetTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetTournament.');
        }
    }

    /**
     */
    tournamentControllerGetTournamentContext(requestParameters: TournamentControllerGetTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetTournament = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerGetTournamentRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetTournamentMatchesRaw(requestParameters: TournamentControllerGetTournamentMatchesRequest): Promise<runtime.ApiResponse<Array<TournamentBracketMatchDto>>> {
        this.tournamentControllerGetTournamentMatchesValidation(requestParameters);
        const context = this.tournamentControllerGetTournamentMatchesContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TournamentBracketMatchDtoFromJSON));
    }



    /**
     */
    private tournamentControllerGetTournamentMatchesValidation(requestParameters: TournamentControllerGetTournamentMatchesRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetTournamentMatches.');
        }
    }

    /**
     */
    tournamentControllerGetTournamentMatchesContext(requestParameters: TournamentControllerGetTournamentMatchesRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/matches`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetTournamentMatches = async (id: number): Promise<Array<TournamentBracketMatchDto>> => {
        const response = await this.tournamentControllerGetTournamentMatchesRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetTournamentStandingsRaw(requestParameters: TournamentControllerGetTournamentStandingsRequest): Promise<runtime.ApiResponse<Array<TournamentStageStandingsResultDto>>> {
        this.tournamentControllerGetTournamentStandingsValidation(requestParameters);
        const context = this.tournamentControllerGetTournamentStandingsContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TournamentStageStandingsResultDtoFromJSON));
    }



    /**
     */
    private tournamentControllerGetTournamentStandingsValidation(requestParameters: TournamentControllerGetTournamentStandingsRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetTournamentStandings.');
        }
    }

    /**
     */
    tournamentControllerGetTournamentStandingsContext(requestParameters: TournamentControllerGetTournamentStandingsRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/standings`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetTournamentStandings = async (id: number): Promise<Array<TournamentStageStandingsResultDto>> => {
        const response = await this.tournamentControllerGetTournamentStandingsRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerInviteToRegistrationRaw(requestParameters: TournamentControllerInviteToRegistrationRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerInviteToRegistrationValidation(requestParameters);
        const context = this.tournamentControllerInviteToRegistrationContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerInviteToRegistrationValidation(requestParameters: TournamentControllerInviteToRegistrationRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerInviteToRegistration.');
        }
        if (requestParameters.tournamentInviteToRegistrationDto === null || requestParameters.tournamentInviteToRegistrationDto === undefined) {
            throw new runtime.RequiredError('tournamentInviteToRegistrationDto','Required parameter requestParameters.tournamentInviteToRegistrationDto was null or undefined when calling tournamentControllerInviteToRegistration.');
        }
    }

    /**
     */
    tournamentControllerInviteToRegistrationContext(requestParameters: TournamentControllerInviteToRegistrationRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/invite_to_registration`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentInviteToRegistrationDtoToJSON(requestParameters.tournamentInviteToRegistrationDto),
        };
    }

    /**
     */
    tournamentControllerInviteToRegistration = async (id: number, tournamentInviteToRegistrationDto: TournamentInviteToRegistrationDto): Promise<void> => {
        await this.tournamentControllerInviteToRegistrationRaw({ id: id, tournamentInviteToRegistrationDto: tournamentInviteToRegistrationDto });
    }

    /**
     */
    private async tournamentControllerListTournamentsRaw(): Promise<runtime.ApiResponse<Array<TournamentTournamentDto>>> {
        this.tournamentControllerListTournamentsValidation();
        const context = this.tournamentControllerListTournamentsContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TournamentTournamentDtoFromJSON));
    }



    /**
     */
    private tournamentControllerListTournamentsValidation() {
    }

    /**
     */
    tournamentControllerListTournamentsContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerListTournaments = async (): Promise<Array<TournamentTournamentDto>> => {
        const response = await this.tournamentControllerListTournamentsRaw();
        return await response.value();
    }

    /**
     */
    private async tournamentControllerPublishTournamentRaw(requestParameters: TournamentControllerPublishTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerPublishTournamentValidation(requestParameters);
        const context = this.tournamentControllerPublishTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerPublishTournamentValidation(requestParameters: TournamentControllerPublishTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerPublishTournament.');
        }
    }

    /**
     */
    tournamentControllerPublishTournamentContext(requestParameters: TournamentControllerPublishTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/publish_tournament`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerPublishTournament = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerPublishTournamentRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerRegisterRaw(requestParameters: TournamentControllerRegisterRequest): Promise<runtime.ApiResponse<number>> {
        this.tournamentControllerRegisterValidation(requestParameters);
        const context = this.tournamentControllerRegisterContext(requestParameters);
        const response = await this.request(context);

        return new runtime.TextApiResponse(response) as any;
    }



    /**
     */
    private tournamentControllerRegisterValidation(requestParameters: TournamentControllerRegisterRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerRegister.');
        }
        if (requestParameters.tournamentRegisterAsPartyDto === null || requestParameters.tournamentRegisterAsPartyDto === undefined) {
            throw new runtime.RequiredError('tournamentRegisterAsPartyDto','Required parameter requestParameters.tournamentRegisterAsPartyDto was null or undefined when calling tournamentControllerRegister.');
        }
    }

    /**
     */
    tournamentControllerRegisterContext(requestParameters: TournamentControllerRegisterRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/register`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentRegisterAsPartyDtoToJSON(requestParameters.tournamentRegisterAsPartyDto),
        };
    }

    /**
     */
    tournamentControllerRegister = async (id: number, tournamentRegisterAsPartyDto: TournamentRegisterAsPartyDto): Promise<number> => {
        const response = await this.tournamentControllerRegisterRaw({ id: id, tournamentRegisterAsPartyDto: tournamentRegisterAsPartyDto });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerReplyRegistrationInvitationRaw(requestParameters: TournamentControllerReplyRegistrationInvitationRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerReplyRegistrationInvitationValidation(requestParameters);
        const context = this.tournamentControllerReplyRegistrationInvitationContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerReplyRegistrationInvitationValidation(requestParameters: TournamentControllerReplyRegistrationInvitationRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerReplyRegistrationInvitation.');
        }
        if (requestParameters.tournamentReplyRegistrationInvitationDto === null || requestParameters.tournamentReplyRegistrationInvitationDto === undefined) {
            throw new runtime.RequiredError('tournamentReplyRegistrationInvitationDto','Required parameter requestParameters.tournamentReplyRegistrationInvitationDto was null or undefined when calling tournamentControllerReplyRegistrationInvitation.');
        }
    }

    /**
     */
    tournamentControllerReplyRegistrationInvitationContext(requestParameters: TournamentControllerReplyRegistrationInvitationRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/reply_to_registration_invitation`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentReplyRegistrationInvitationDtoToJSON(requestParameters.tournamentReplyRegistrationInvitationDto),
        };
    }

    /**
     */
    tournamentControllerReplyRegistrationInvitation = async (id: number, tournamentReplyRegistrationInvitationDto: TournamentReplyRegistrationInvitationDto): Promise<void> => {
        await this.tournamentControllerReplyRegistrationInvitationRaw({ id: id, tournamentReplyRegistrationInvitationDto: tournamentReplyRegistrationInvitationDto });
    }

    /**
     */
    private async tournamentControllerResetGameDataRaw(requestParameters: TournamentControllerResetGameDataRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerResetGameDataValidation(requestParameters);
        const context = this.tournamentControllerResetGameDataContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerResetGameDataValidation(requestParameters: TournamentControllerResetGameDataRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerResetGameData.');
        }
        if (requestParameters.tournamentResetGameDataDto === null || requestParameters.tournamentResetGameDataDto === undefined) {
            throw new runtime.RequiredError('tournamentResetGameDataDto','Required parameter requestParameters.tournamentResetGameDataDto was null or undefined when calling tournamentControllerResetGameData.');
        }
    }

    /**
     */
    tournamentControllerResetGameDataContext(requestParameters: TournamentControllerResetGameDataRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/reset_game_data`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentResetGameDataDtoToJSON(requestParameters.tournamentResetGameDataDto),
        };
    }

    /**
     */
    tournamentControllerResetGameData = async (id: number, tournamentResetGameDataDto: TournamentResetGameDataDto): Promise<void> => {
        await this.tournamentControllerResetGameDataRaw({ id: id, tournamentResetGameDataDto: tournamentResetGameDataDto });
    }

    /**
     */
    private async tournamentControllerScheduleMatchRaw(requestParameters: TournamentControllerScheduleMatchRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerScheduleMatchValidation(requestParameters);
        const context = this.tournamentControllerScheduleMatchContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerScheduleMatchValidation(requestParameters: TournamentControllerScheduleMatchRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerScheduleMatch.');
        }
        if (requestParameters.tournamentScheduleTournamentGameDto === null || requestParameters.tournamentScheduleTournamentGameDto === undefined) {
            throw new runtime.RequiredError('tournamentScheduleTournamentGameDto','Required parameter requestParameters.tournamentScheduleTournamentGameDto was null or undefined when calling tournamentControllerScheduleMatch.');
        }
    }

    /**
     */
    tournamentControllerScheduleMatchContext(requestParameters: TournamentControllerScheduleMatchRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/schedule_game`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentScheduleTournamentGameDtoToJSON(requestParameters.tournamentScheduleTournamentGameDto),
        };
    }

    /**
     */
    tournamentControllerScheduleMatch = async (id: number, tournamentScheduleTournamentGameDto: TournamentScheduleTournamentGameDto): Promise<void> => {
        await this.tournamentControllerScheduleMatchRaw({ id: id, tournamentScheduleTournamentGameDto: tournamentScheduleTournamentGameDto });
    }

    /**
     */
    private async tournamentControllerSetGameWinnerRaw(requestParameters: TournamentControllerSetGameWinnerRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerSetGameWinnerValidation(requestParameters);
        const context = this.tournamentControllerSetGameWinnerContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerSetGameWinnerValidation(requestParameters: TournamentControllerSetGameWinnerRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerSetGameWinner.');
        }
        if (requestParameters.tournamentSetGameWinnerDto === null || requestParameters.tournamentSetGameWinnerDto === undefined) {
            throw new runtime.RequiredError('tournamentSetGameWinnerDto','Required parameter requestParameters.tournamentSetGameWinnerDto was null or undefined when calling tournamentControllerSetGameWinner.');
        }
    }

    /**
     */
    tournamentControllerSetGameWinnerContext(requestParameters: TournamentControllerSetGameWinnerRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/set_game_winner`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentSetGameWinnerDtoToJSON(requestParameters.tournamentSetGameWinnerDto),
        };
    }

    /**
     */
    tournamentControllerSetGameWinner = async (id: number, tournamentSetGameWinnerDto: TournamentSetGameWinnerDto): Promise<void> => {
        await this.tournamentControllerSetGameWinnerRaw({ id: id, tournamentSetGameWinnerDto: tournamentSetGameWinnerDto });
    }

    /**
     */
    private async tournamentControllerStartGameRaw(requestParameters: TournamentControllerStartGameRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerStartGameValidation(requestParameters);
        const context = this.tournamentControllerStartGameContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerStartGameValidation(requestParameters: TournamentControllerStartGameRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerStartGame.');
        }
        if (requestParameters.tournamentStartGameDto === null || requestParameters.tournamentStartGameDto === undefined) {
            throw new runtime.RequiredError('tournamentStartGameDto','Required parameter requestParameters.tournamentStartGameDto was null or undefined when calling tournamentControllerStartGame.');
        }
    }

    /**
     */
    tournamentControllerStartGameContext(requestParameters: TournamentControllerStartGameRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/start_game`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentStartGameDtoToJSON(requestParameters.tournamentStartGameDto),
        };
    }

    /**
     */
    tournamentControllerStartGame = async (id: number, tournamentStartGameDto: TournamentStartGameDto): Promise<void> => {
        await this.tournamentControllerStartGameRaw({ id: id, tournamentStartGameDto: tournamentStartGameDto });
    }

    /**
     */
    private async tournamentControllerStartTournamentRaw(requestParameters: TournamentControllerStartTournamentRequest): Promise<runtime.ApiResponse<TournamentBracketDto>> {
        this.tournamentControllerStartTournamentValidation(requestParameters);
        const context = this.tournamentControllerStartTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentBracketDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerStartTournamentValidation(requestParameters: TournamentControllerStartTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerStartTournament.');
        }
    }

    /**
     */
    tournamentControllerStartTournamentContext(requestParameters: TournamentControllerStartTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/generate_bracket`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerStartTournament = async (id: number): Promise<TournamentBracketDto> => {
        const response = await this.tournamentControllerStartTournamentRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerUnregisterRaw(requestParameters: TournamentControllerUnregisterRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerUnregisterValidation(requestParameters);
        const context = this.tournamentControllerUnregisterContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerUnregisterValidation(requestParameters: TournamentControllerUnregisterRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerUnregister.');
        }
        if (requestParameters.tournamentUnregisterPlayerDto === null || requestParameters.tournamentUnregisterPlayerDto === undefined) {
            throw new runtime.RequiredError('tournamentUnregisterPlayerDto','Required parameter requestParameters.tournamentUnregisterPlayerDto was null or undefined when calling tournamentControllerUnregister.');
        }
    }

    /**
     */
    tournamentControllerUnregisterContext(requestParameters: TournamentControllerUnregisterRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/unregister`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentUnregisterPlayerDtoToJSON(requestParameters.tournamentUnregisterPlayerDto),
        };
    }

    /**
     */
    tournamentControllerUnregister = async (id: number, tournamentUnregisterPlayerDto: TournamentUnregisterPlayerDto): Promise<void> => {
        await this.tournamentControllerUnregisterRaw({ id: id, tournamentUnregisterPlayerDto: tournamentUnregisterPlayerDto });
    }

    /**
     */
    private async tournamentControllerUpdateTournamentRaw(requestParameters: TournamentControllerUpdateTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerUpdateTournamentValidation(requestParameters);
        const context = this.tournamentControllerUpdateTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerUpdateTournamentValidation(requestParameters: TournamentControllerUpdateTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerUpdateTournament.');
        }
        if (requestParameters.tournamentUpdateTournamentDto === null || requestParameters.tournamentUpdateTournamentDto === undefined) {
            throw new runtime.RequiredError('tournamentUpdateTournamentDto','Required parameter requestParameters.tournamentUpdateTournamentDto was null or undefined when calling tournamentControllerUpdateTournament.');
        }
    }

    /**
     */
    tournamentControllerUpdateTournamentContext(requestParameters: TournamentControllerUpdateTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentUpdateTournamentDtoToJSON(requestParameters.tournamentUpdateTournamentDto),
        };
    }

    /**
     */
    tournamentControllerUpdateTournament = async (id: number, tournamentUpdateTournamentDto: TournamentUpdateTournamentDto): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerUpdateTournamentRaw({ id: id, tournamentUpdateTournamentDto: tournamentUpdateTournamentDto });
        return await response.value();
    }

}
