/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from "../runtime";

import {
  TournamentBracketDto,
  TournamentBracketDtoFromJSON,
  TournamentConfirmRegistrationDto,
  TournamentConfirmRegistrationDtoToJSON,
  TournamentCreateTournamentDto,
  TournamentCreateTournamentDtoToJSON,
  TournamentRegisterAsPartyDto,
  TournamentRegisterAsPartyDtoToJSON,
  TournamentSetGameWinnerDto,
  TournamentSetGameWinnerDtoToJSON,
  TournamentStartGameDto,
  TournamentStartGameDtoToJSON,
  TournamentTournamentBracketInfoDto,
  TournamentTournamentBracketInfoDtoFromJSON,
  TournamentTournamentDto,
  TournamentTournamentDtoFromJSON,
  TournamentUpdateTournamentDto,
  TournamentUpdateTournamentDtoToJSON,
} from "../models";

export interface TournamentControllerAutoScheduleBracketRequest {
  id: number;
}

export interface TournamentControllerConfirmRegistrationRequest {
    id: number;
    tournamentConfirmRegistrationDto: TournamentConfirmRegistrationDto;
}

export interface TournamentControllerCreateTournamentRequest {
    tournamentCreateTournamentDto: TournamentCreateTournamentDto;
}

export interface TournamentControllerEndReadyCheckRequest {
    id: number;
}

export interface TournamentControllerEndRegistrationRequest {
    id: number;
}

export interface TournamentControllerGetBracketRequest {
    id: number;
}

export interface TournamentControllerGetBracketRenderRequest {
    id: number;
}

export interface TournamentControllerGetTournamentRequest {
    id: number;
}

export interface TournamentControllerPublishTournamentRequest {
    id: number;
}

export interface TournamentControllerRegisterRequest {
    id: number;
    tournamentRegisterAsPartyDto: TournamentRegisterAsPartyDto;
}

export interface TournamentControllerSetGameWinnerRequest {
    id: number;
    tournamentSetGameWinnerDto: TournamentSetGameWinnerDto;
}

export interface TournamentControllerStartGameRequest {
    id: number;
    tournamentStartGameDto: TournamentStartGameDto;
}

export interface TournamentControllerStartTournamentRequest {
    id: number;
}

export interface TournamentControllerUpdateTournamentRequest {
    id: number;
    tournamentUpdateTournamentDto: TournamentUpdateTournamentDto;
}

/**
 *
 */
export class TournamentApi extends runtime.BaseAPI {

    /**
     */
    tournamentControllerGetBracketContext(requestParameters: TournamentControllerGetBracketRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/bracket`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetBracket = async (id: number): Promise<TournamentBracketDto> => {
        const response = await this.tournamentControllerGetBracketRaw({ id: id });
        return await response.value();
    }

    /**
     */
    tournamentControllerAutoScheduleBracketContext(requestParameters: TournamentControllerAutoScheduleBracketRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/auto_schedule_bracket`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerAutoScheduleBracket = async (id: number): Promise<TournamentBracketDto> => {
        const response = await this.tournamentControllerAutoScheduleBracketRaw({ id: id });
        return await response.value();
    }

    /**
     */
    tournamentControllerGetBracketRenderContext(requestParameters: TournamentControllerGetBracketRenderRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/bracket_render`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetBracketRender = async (id: number): Promise<TournamentTournamentBracketInfoDto> => {
        const response = await this.tournamentControllerGetBracketRenderRaw({ id: id });
        return await response.value();
    }

    /**
     */
    tournamentControllerConfirmRegistrationContext(requestParameters: TournamentControllerConfirmRegistrationRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/confirm_registration`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentConfirmRegistrationDtoToJSON(requestParameters.tournamentConfirmRegistrationDto),
        };
    }

    /**
     */
    tournamentControllerConfirmRegistration = async (id: number, tournamentConfirmRegistrationDto: TournamentConfirmRegistrationDto): Promise<void> => {
        await this.tournamentControllerConfirmRegistrationRaw({ id: id, tournamentConfirmRegistrationDto: tournamentConfirmRegistrationDto });
    }

    /**
     */
    tournamentControllerGetTournamentContext(requestParameters: TournamentControllerGetTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerGetTournament = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerGetTournamentRaw({ id: id });
        return await response.value();
    }

    /**
     */
    tournamentControllerCreateTournamentContext(requestParameters: TournamentControllerCreateTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentCreateTournamentDtoToJSON(requestParameters.tournamentCreateTournamentDto),
        };
    }

    /**
     */
    tournamentControllerCreateTournament = async (tournamentCreateTournamentDto: TournamentCreateTournamentDto): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerCreateTournamentRaw({ tournamentCreateTournamentDto: tournamentCreateTournamentDto });
        return await response.value();
    }

    /**
     */
    tournamentControllerListTournamentsContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerListTournaments = async (): Promise<Array<TournamentTournamentDto>> => {
        const response = await this.tournamentControllerListTournamentsRaw();
        return await response.value();
    }

    /**
     */
    tournamentControllerEndReadyCheckContext(requestParameters: TournamentControllerEndReadyCheckRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/end_ready_check`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerEndReadyCheck = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerEndReadyCheckRaw({ id: id });
        return await response.value();
    }

    /**
     */
    tournamentControllerPublishTournamentContext(requestParameters: TournamentControllerPublishTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/publish_tournament`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerPublishTournament = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerPublishTournamentRaw({ id: id });
        return await response.value();
    }

    /**
     */
    tournamentControllerEndRegistrationContext(requestParameters: TournamentControllerEndRegistrationRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/end_registration`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerEndRegistration = async (id: number): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerEndRegistrationRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetBracketRaw(requestParameters: TournamentControllerGetBracketRequest): Promise<runtime.ApiResponse<TournamentBracketDto>> {
        this.tournamentControllerGetBracketValidation(requestParameters);
        const context = this.tournamentControllerGetBracketContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentBracketDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerGetBracketValidation(requestParameters: TournamentControllerGetBracketRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetBracket.');
        }
    }

    /**
     */
    tournamentControllerRegisterContext(requestParameters: TournamentControllerRegisterRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/register`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentRegisterAsPartyDtoToJSON(requestParameters.tournamentRegisterAsPartyDto),
        };
    }

    /**
     */
    tournamentControllerRegister = async (id: number, tournamentRegisterAsPartyDto: TournamentRegisterAsPartyDto): Promise<number> => {
        const response = await this.tournamentControllerRegisterRaw({ id: id, tournamentRegisterAsPartyDto: tournamentRegisterAsPartyDto });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerGetBracketRenderRaw(requestParameters: TournamentControllerGetBracketRenderRequest): Promise<runtime.ApiResponse<TournamentTournamentBracketInfoDto>> {
        this.tournamentControllerGetBracketRenderValidation(requestParameters);
        const context = this.tournamentControllerGetBracketRenderContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentBracketInfoDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerGetBracketRenderValidation(requestParameters: TournamentControllerGetBracketRenderRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetBracketRender.');
        }
    }

    /**
     */
    tournamentControllerSetGameWinnerContext(requestParameters: TournamentControllerSetGameWinnerRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/set_game_winner`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentSetGameWinnerDtoToJSON(requestParameters.tournamentSetGameWinnerDto),
        };
    }

    /**
     */
    tournamentControllerSetGameWinner = async (id: number, tournamentSetGameWinnerDto: TournamentSetGameWinnerDto): Promise<void> => {
        await this.tournamentControllerSetGameWinnerRaw({ id: id, tournamentSetGameWinnerDto: tournamentSetGameWinnerDto });
    }

    /**
     */
    private async tournamentControllerGetTournamentRaw(requestParameters: TournamentControllerGetTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerGetTournamentValidation(requestParameters);
        const context = this.tournamentControllerGetTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerGetTournamentValidation(requestParameters: TournamentControllerGetTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerGetTournament.');
        }
    }

    /**
     */
    tournamentControllerStartGameContext(requestParameters: TournamentControllerStartGameRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}/start_game`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentStartGameDtoToJSON(requestParameters.tournamentStartGameDto),
        };
    }

    /**
     */
    tournamentControllerStartGame = async (id: number, tournamentStartGameDto: TournamentStartGameDto): Promise<void> => {
        await this.tournamentControllerStartGameRaw({ id: id, tournamentStartGameDto: tournamentStartGameDto });
    }

    /**
     */
    private async tournamentControllerListTournamentsRaw(): Promise<runtime.ApiResponse<Array<TournamentTournamentDto>>> {
        this.tournamentControllerListTournamentsValidation();
        const context = this.tournamentControllerListTournamentsContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TournamentTournamentDtoFromJSON));
    }



    /**
     */
    private tournamentControllerListTournamentsValidation() {
    }

    /**
     */
    tournamentControllerStartTournamentContext(requestParameters: TournamentControllerStartTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/tournament/{id}/generate_bracket`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    tournamentControllerStartTournament = async (id: number): Promise<TournamentBracketDto> => {
        const response = await this.tournamentControllerStartTournamentRaw({ id: id });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerPublishTournamentRaw(requestParameters: TournamentControllerPublishTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerPublishTournamentValidation(requestParameters);
        const context = this.tournamentControllerPublishTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerPublishTournamentValidation(requestParameters: TournamentControllerPublishTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerPublishTournament.');
        }
    }

    /**
     */
    tournamentControllerUpdateTournamentContext(requestParameters: TournamentControllerUpdateTournamentRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        return {
            path: `/tournament/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TournamentUpdateTournamentDtoToJSON(requestParameters.tournamentUpdateTournamentDto),
        };
    }

    /**
     */
    tournamentControllerUpdateTournament = async (id: number, tournamentUpdateTournamentDto: TournamentUpdateTournamentDto): Promise<TournamentTournamentDto> => {
        const response = await this.tournamentControllerUpdateTournamentRaw({ id: id, tournamentUpdateTournamentDto: tournamentUpdateTournamentDto });
        return await response.value();
    }

    /**
     */
    private async tournamentControllerRegisterRaw(requestParameters: TournamentControllerRegisterRequest): Promise<runtime.ApiResponse<number>> {
        this.tournamentControllerRegisterValidation(requestParameters);
        const context = this.tournamentControllerRegisterContext(requestParameters);
        const response = await this.request(context);

        return new runtime.TextApiResponse(response) as any;
    }



    /**
     */
    private tournamentControllerRegisterValidation(requestParameters: TournamentControllerRegisterRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerRegister.');
        }
        if (requestParameters.tournamentRegisterAsPartyDto === null || requestParameters.tournamentRegisterAsPartyDto === undefined) {
            throw new runtime.RequiredError('tournamentRegisterAsPartyDto','Required parameter requestParameters.tournamentRegisterAsPartyDto was null or undefined when calling tournamentControllerRegister.');
        }
    }

    /**
     */
    private async tournamentControllerAutoScheduleBracketRaw(requestParameters: TournamentControllerAutoScheduleBracketRequest): Promise<runtime.ApiResponse<TournamentBracketDto>> {
        this.tournamentControllerAutoScheduleBracketValidation(requestParameters);
        const context = this.tournamentControllerAutoScheduleBracketContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentBracketDtoFromJSON(jsonValue));
    }

    /**
     */
    private tournamentControllerAutoScheduleBracketValidation(requestParameters: TournamentControllerAutoScheduleBracketRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerAutoScheduleBracket.');
        }
    }

    /**
     */
    private async tournamentControllerSetGameWinnerRaw(requestParameters: TournamentControllerSetGameWinnerRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerSetGameWinnerValidation(requestParameters);
        const context = this.tournamentControllerSetGameWinnerContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerSetGameWinnerValidation(requestParameters: TournamentControllerSetGameWinnerRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerSetGameWinner.');
        }
        if (requestParameters.tournamentSetGameWinnerDto === null || requestParameters.tournamentSetGameWinnerDto === undefined) {
            throw new runtime.RequiredError('tournamentSetGameWinnerDto','Required parameter requestParameters.tournamentSetGameWinnerDto was null or undefined when calling tournamentControllerSetGameWinner.');
        }
    }

    /**
     */
    private async tournamentControllerConfirmRegistrationRaw(requestParameters: TournamentControllerConfirmRegistrationRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerConfirmRegistrationValidation(requestParameters);
        const context = this.tournamentControllerConfirmRegistrationContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    private tournamentControllerConfirmRegistrationValidation(requestParameters: TournamentControllerConfirmRegistrationRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerConfirmRegistration.');
        }
        if (requestParameters.tournamentConfirmRegistrationDto === null || requestParameters.tournamentConfirmRegistrationDto === undefined) {
            throw new runtime.RequiredError('tournamentConfirmRegistrationDto','Required parameter requestParameters.tournamentConfirmRegistrationDto was null or undefined when calling tournamentControllerConfirmRegistration.');
        }
    }

    /**
     */
    private async tournamentControllerStartGameRaw(requestParameters: TournamentControllerStartGameRequest): Promise<runtime.ApiResponse<void>> {
        this.tournamentControllerStartGameValidation(requestParameters);
        const context = this.tournamentControllerStartGameContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private tournamentControllerStartGameValidation(requestParameters: TournamentControllerStartGameRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerStartGame.');
        }
        if (requestParameters.tournamentStartGameDto === null || requestParameters.tournamentStartGameDto === undefined) {
            throw new runtime.RequiredError('tournamentStartGameDto','Required parameter requestParameters.tournamentStartGameDto was null or undefined when calling tournamentControllerStartGame.');
        }
    }

    /**
     */
    private async tournamentControllerCreateTournamentRaw(requestParameters: TournamentControllerCreateTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerCreateTournamentValidation(requestParameters);
        const context = this.tournamentControllerCreateTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }

    /**
     */
    private tournamentControllerCreateTournamentValidation(requestParameters: TournamentControllerCreateTournamentRequest) {
        if (requestParameters.tournamentCreateTournamentDto === null || requestParameters.tournamentCreateTournamentDto === undefined) {
            throw new runtime.RequiredError('tournamentCreateTournamentDto','Required parameter requestParameters.tournamentCreateTournamentDto was null or undefined when calling tournamentControllerCreateTournament.');
        }
    }

    /**
     */
    private async tournamentControllerStartTournamentRaw(requestParameters: TournamentControllerStartTournamentRequest): Promise<runtime.ApiResponse<TournamentBracketDto>> {
        this.tournamentControllerStartTournamentValidation(requestParameters);
        const context = this.tournamentControllerStartTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentBracketDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerStartTournamentValidation(requestParameters: TournamentControllerStartTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerStartTournament.');
        }
    }

    /**
     */
    private async tournamentControllerEndReadyCheckRaw(requestParameters: TournamentControllerEndReadyCheckRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerEndReadyCheckValidation(requestParameters);
        const context = this.tournamentControllerEndReadyCheckContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }

    /**
     */
    private tournamentControllerEndReadyCheckValidation(requestParameters: TournamentControllerEndReadyCheckRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerEndReadyCheck.');
        }
    }

    /**
     */
    private async tournamentControllerUpdateTournamentRaw(requestParameters: TournamentControllerUpdateTournamentRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerUpdateTournamentValidation(requestParameters);
        const context = this.tournamentControllerUpdateTournamentContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }



    /**
     */
    private tournamentControllerUpdateTournamentValidation(requestParameters: TournamentControllerUpdateTournamentRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerUpdateTournament.');
        }
        if (requestParameters.tournamentUpdateTournamentDto === null || requestParameters.tournamentUpdateTournamentDto === undefined) {
            throw new runtime.RequiredError('tournamentUpdateTournamentDto','Required parameter requestParameters.tournamentUpdateTournamentDto was null or undefined when calling tournamentControllerUpdateTournament.');
        }
    }

    /**
     */
    private async tournamentControllerEndRegistrationRaw(requestParameters: TournamentControllerEndRegistrationRequest): Promise<runtime.ApiResponse<TournamentTournamentDto>> {
        this.tournamentControllerEndRegistrationValidation(requestParameters);
        const context = this.tournamentControllerEndRegistrationContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TournamentTournamentDtoFromJSON(jsonValue));
    }

    /**
     */
    private tournamentControllerEndRegistrationValidation(requestParameters: TournamentControllerEndRegistrationRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling tournamentControllerEndRegistration.');
        }
    }

}
