name: Deploy

on:
  workflow_run:
    workflows: [ "Build" ]  # must match the name in your build workflow
    branches: master
    types:
      - completed

jobs:
  deploy:
    name: Rollout Restart Deployment
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Rollout restart deployment
        run: |
          source .github/deploy.env
          kubectl rollout restart deployment "$DEPLOYMENT" -n "$NAMESPACE"
          kubectl rollout status deployment "$DEPLOYMENT" -n "$NAMESPACE"
